import { Platform } from "react-native";
import { outOfStockMessage } from "~root/Lib/AlertsHelper";

export const MyListsData = [
  {
    listName: "4",
    productCount: 2,
    productList: [
      {
        availableForPickup: true,
        barcodesPM: "6924328315803",
        code: "4860850",
        expressOrder: true,
        hasNoQuantity: 0,
        images: [
          {
            altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
            format: "zoom",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
          },
          {
            altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
            format: "product",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
          },
          {
            altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
            format: "thumbnail",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
          },
          {
            altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
            format: "cartIcon",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
          },
        ],
        kitProductFlag: false,
        manufacturer: "WORX",
        name: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
        perpetualFlag: false,
        productTypeCodeEnum: "N",
        sellOrderMultiple: 0,
        timberProductFlag: false,
        unitCode: "EA",
        uomFormat: "5",
      },
      {
        availableForPickup: true,
        barcodesPM: "9416342540271",
        code: "3970950",
        expressOrder: true,
        hasNoQuantity: 3,
        images: [
          {
            altText: "Value Disposable Chip Paint Brush 3 pack",
            format: "zoom",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
          },
          {
            altText: "Value Disposable Chip Paint Brush 3 pack",
            format: "product",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
          },
          {
            altText: "Value Disposable Chip Paint Brush 3 pack",
            format: "thumbnail",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
          },
          {
            altText: "Value Disposable Chip Paint Brush 3 pack",
            format: "cartIcon",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
          },
        ],
        kitProductFlag: false,
        manufacturer: "PAL",
        name: "Value Disposable Chip Paint Brush 3 pack",
        perpetualFlag: false,
        productTypeCodeEnum: "N",
        sellOrderMultiple: 0,
        timberProductFlag: false,
        unitCode: "EA",
        uomFormat: "5",
        hasNoUOM: {},
      },
    ],
    userID: "shashika.abeysuriya@fbu.com",
  },
];

export const ExpectedListImagesData = [
  [
    {
      altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
      format: "thumbnail",
      imageType: "PRIMARY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
    },
    {
      altText: "Value Disposable Chip Paint Brush 3 pack",
      format: "thumbnail",
      imageType: "PRIMARY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
    },
  ],
];

export const ExpectConsolidatedMyListData = [
  {
    images: [
      {
        altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
        format: "thumbnail",
        imageType: "PRIMARY",
        url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
      },
      {
        altText: "Value Disposable Chip Paint Brush 3 pack",
        format: "thumbnail",
        imageType: "PRIMARY",
        url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
      },
    ],
    listName: "4",
    productCount: 2,
    productList: [
      {
        availableForPickup: true,
        barcodesPM: "6924328315803",
        code: "4860850",
        expressOrder: true,
        hasNoQuantity: 0,
        images: [
          {
            altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
            format: "zoom",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
          },
          {
            altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
            format: "product",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
          },
          {
            altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
            format: "thumbnail",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
          },
          {
            altText: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
            format: "cartIcon",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
          },
        ],
        kitProductFlag: false,
        manufacturer: "WORX",
        name: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
        perpetualFlag: false,
        productTypeCodeEnum: "N",
        sellOrderMultiple: 0,
        timberProductFlag: false,
        unitCode: "EA",
        uomFormat: "5",
      },
      {
        availableForPickup: true,
        barcodesPM: "9416342540271",
        code: "3970950",
        expressOrder: true,
        hasNoQuantity: 3,
        images: [
          {
            altText: "Value Disposable Chip Paint Brush 3 pack",
            format: "zoom",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
          },
          {
            altText: "Value Disposable Chip Paint Brush 3 pack",
            format: "product",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
          },
          {
            altText: "Value Disposable Chip Paint Brush 3 pack",
            format: "thumbnail",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
          },
          {
            altText: "Value Disposable Chip Paint Brush 3 pack",
            format: "cartIcon",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
          },
        ],
        kitProductFlag: false,
        manufacturer: "PAL",
        name: "Value Disposable Chip Paint Brush 3 pack",
        perpetualFlag: false,
        productTypeCodeEnum: "N",
        sellOrderMultiple: 0,
        timberProductFlag: false,
        unitCode: "EA",
        uomFormat: "5",
        hasNoUOM: {},
      },
    ],
    userID: "shashika.abeysuriya@fbu.com",
  },
];

export const MyListDetailsData = [
  {
    AccountCustomerId: "ANTGA",
    Availability: outOfStockMessage,
    BranchId: "362",
    Brand: "WORX",
    Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Worx_WX530.9.jpg",
    IsExpressOrder: false,
    IsTimberProduct: false,
    JobAccountId: "ANTGA",
    Price: "125.68",
    ProductDescription: "Worx Cordless Circular Saw Skin 165mm 20V 4900rpm WX530.9",
    SKU: "4860850",
    SelectedMultiple: "0",
    StockQuantity: "1",
    UOM: "EA",
    UniqueId: "4860850-0",
    sellOrderMultiple: "0",
    timberProductFlag: false,
    uomFormat: "5",
  },
  {
    AccountCustomerId: "ANTGA",
    Availability: "7 in stock",
    BranchId: "362",
    Brand: "PAL",
    Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
    IsExpressOrder: true,
    IsTimberProduct: false,
    JobAccountId: "ANTGA",
    Price: "5.32",
    ProductDescription: "Value Disposable Chip Paint Brush 3 pack",
    SKU: "3970950",
    SelectedMultiple: "0",
    StockQuantity: "7",
    UOM: "EA",
    UniqueId: "3970950-0",
    sellOrderMultiple: "0",
    timberProductFlag: false,
    uomFormat: "5",
  },
];

export const ExpectedMyListDetailData = [
  {
    AccountCustomerId: "ANTGA",
    Availability: "7 in stock",
    BranchId: "362",
    Brand: "PAL",
    Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/3970950.jpg",
    IsExpressOrder: true,
    IsTimberProduct: false,
    JobAccountId: "ANTGA",
    Price: "5.32",
    ProductDescription: "Value Disposable Chip Paint Brush 3 pack",
    SKU: "3970950",
    SelectedMultiple: "0",
    StockQuantity: "7",
    UOM: "EA",
    UniqueId: "3970950-0",
    sellOrderMultiple: "0",
    timberProductFlag: false,
    uomFormat: "5",
  },
];

export const OutOfStockProduct = {
  availableForPickup: false,
  baseOptions: [],
  categories: [
    {
      code: "BW15UA",
      name: "Steel Reinfrcng Bar",
    },
  ],
  classifications: [
    {
      code: "Specification",
      features: [
        {
          code: "Weight",
          comparable: false,
          featureUnit: {
            name: "Kilogram",
            symbol: "KGM",
            unitType: "KGM",
          },
          featureValues: [
            {
              value: "0.08",
            },
          ],
          name: "Weight",
          range: false,
        },
      ],
      name: "Specifications",
    },
  ],
  code: "3500527",
  configurable: false,
  expressOrder: false,
  hasNoQuantity: 0,
  kitProductFlag: false,
  manufacturer: "FREO",
  name: "FREO REBAR HD16 6M DEFORMED 500E 7414069",
  numberOfReviews: 0,
  perpetualFlag: false,
  price: {
    currencyIso: "NZD",
    formattedValue: "$35.72",
    priceType: "BUY",
    value: 35.72,
  },
  priceRange: {},
  productTypeCodeEnum: "N",
  purchasable: true,
  sellOrderMultiple: 0,
  stock: {
    pmStockQuantity: "0",
    statusCode: "3",
    stockLevelStatus: "outOfStock",
  },
  summary: "",
  timberProductFlag: false,
  type: "pmProductWsDTO",
  unitCode: "EA",
  uomFormat: "5",
};

export const InStockProduct = {
  availableForPickup: false,
  barcodesPM: "9416561002826",
  baseOptions: [],
  categories: [
    {
      code: "CC18AH",
      name: "Loose Nails Roofing",
    },
  ],
  classifications: [
    {
      code: "Specification",
      features: [
        {
          code: "Weight",
          comparable: false,
          featureUnit: {
            name: "Kilogram",
            symbol: "KGM",
            unitType: "KGM",
          },
          featureValues: [
            {
              value: "5.0",
            },
          ],
          name: "Weight",
          range: false,
        },
      ],
      name: "Specifications",
    },
  ],
  code: "3537578",
  configurable: false,
  description:
    "The Bremick NU-FIX Roofing Nail in grey colour, is suitable for fixing various profiles in galvanised roofing iron. This nail measuring 4 mm x 75 mm, features bullet head that offers great versatility. Nail with spiral shaft, features steel construction and hot-dipped galvanized finish that offers excellent resistance to corrosion.",
  expressOrder: true,
  hasNoQuantity: 0,
  images: [
    {
      format: "zoom",
      imageType: "PRIMARY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
    },
    {
      format: "product",
      imageType: "PRIMARY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
    },
    {
      format: "thumbnail",
      imageType: "PRIMARY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
    },
    {
      format: "cartIcon",
      imageType: "PRIMARY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
    },
    {
      format: "superZoom",
      imageType: "GALLERY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
    },
    {
      format: "zoom",
      imageType: "GALLERY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
    },
    {
      format: "product",
      imageType: "GALLERY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
    },
    {
      format: "thumbnail",
      imageType: "GALLERY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
    },
    {
      format: "superZoom",
      imageType: "GALLERY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH_1.jpg",
    },
    {
      format: "zoom",
      imageType: "GALLERY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH_1.jpg",
    },
    {
      format: "product",
      imageType: "GALLERY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH_1.jpg",
    },
    {
      format: "thumbnail",
      imageType: "GALLERY",
      url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH_1.jpg",
    },
  ],
  kitProductFlag: false,
  manufacturer: "NZ NAILS",
  name: "NZ Nails NU-FIX Roofing Nail 4 x 75mm Dome Head with Washer Hot Dip Galvanised 075400GNH",
  numberOfReviews: 0,
  perpetualFlag: false,
  price: {
    currencyIso: "NZD",
    formattedValue: "$78.24",
    priceType: "BUY",
    value: 78.24,
  },
  priceRange: {},
  productTypeCodeEnum: "N",
  purchasable: true,
  stock: {
    pmStockQuantity: "5",
    statusCode: "1",
    stockLevelStatus: "inStock",
  },
  summary: "",
  timberProductFlag: false,
  type: "pmProductWsDTO",
  unitCode: "PA",
  uomFormat: "5",
};

export const SampleCartData = {
  data: {
    customer: {
      accountCode: "ANTGA",
      accountName: "Ants General Contracting",
      branchId: "362",
      jobs: {
        jobName: "Ants General Contracting",
        jobNumber: "ANTGA",
      },
      products: [
        {
          customerPriceGstExcl: 78.24,
          customerPriceGstIncl: 89.98,
          quantity: "5",
          retailGstExclusive: 78.24,
          retailGstInclusive: 89.98,
          sku: "3537578",
          statusCode: "1",
          stockMessage: "Stock Available",
        },
        {
          customerPriceGstExcl: 5.3182,
          customerPriceGstIncl: 6.12,
          quantity: "7",
          retailGstExclusive: 5.87,
          retailGstInclusive: 6.75,
          sku: "3970950",
          statusCode: "1",
          stockMessage: "Stock Available",
        },
      ],
      stocksBranchId: "362",
    },
    serviceResult: {
      code: "0",
      message: "",
    },
    transactionId: "cf20a48aea7f48fcad63249da5ae8f58",
    type: "pmProductPriceandStockResponse",
  },
};

export const SampleOrder = [
  {
    Quantity: "2",
    SKU: "3272432",
    ProductDescription: "FREO BAR CHAIR 50/65 LOOSE 81045",
    UOM: "EA",
    Price: "0.46",
    index: 0,
    Availability: "Available",
  },
  {
    Quantity: "2",
    SKU: "2800617",
    ProductDescription: "GIB PLUS 4 4KG JOINTING COMPOUND",
    UOM: "BJ",
    Price: "20.56",
    index: 1,
    Availability: "Available",
  },
  {
    Quantity: "1",
    SKU: "3540937",
    ProductDescription: "TYLOK NAIL PLATE LOOSE 34 X 120MM 4T5S ZC",
    UOM: "EA",
    Price: "0.57",
    index: 2,
    Availability: "Available",
  },
];

export const ExpectedSampleOrder = [
  {
    Availability: "Available",
    Price: "0.46",
    ProductDescription: "FREO BAR CHAIR 50/65 LOOSE 81045",
    Quantity: "2",
    SKU: "3272432",
    UOM: "EA",
    index: 0,
  },
  {
    Availability: "Available",
    Price: "20.56",
    ProductDescription: "GIB PLUS 4 4KG JOINTING COMPOUND",
    Quantity: "2",
    SKU: "2800617",
    UOM: "BJ",
    index: 1,
  },
  {
    Availability: "Available",
    Price: "0.57",
    ProductDescription: "TYLOK NAIL PLATE LOOSE 34 X 120MM 4T5S ZC",
    Quantity: "1",
    SKU: "3540937",
    UOM: "EA",
    index: 2,
  },
];

export const InventoryResponse = {
  data: {
    TransactionId: "00000000000000000001576662775295",
    Branch: {
      BranchId: "362",
      Products: [
        {
          Sku: "3532359",
          Description: "NAIL SS T316 CEMENT 40MM 500G",
          Barcode: "9416561003748",
          UnitOfMeasure: "PA",
          StatusCode: "1",
          StockMessage: "Available",
          Quantity: "7",
          Code: "0",
          Message: "",
        },
      ],
    },
  },
};

export const InventoryItem = {
  Barcode: "9416561003748",
  Code: "0",
  Description: "NAIL SS T316 CEMENT 40MM 500G",
  Message: "",
  Quantity: "7",
  Sku: "3532359",
  StatusCode: "1",
  StockMessage: "Available",
  UnitOfMeasure: "PA",
};

export const InnventoryItem1 = {
  Barcode: "9416561003748",
  Code: "0",
  Description: "NAIL SS T316 CEMENT 40MM 500G",
  Message: "",
  Quantity: "1",
  Sku: "3532359",
  StatusCode: "1",
  StockMessage: "Available",
  UnitOfMeasure: "PA",
};

export const HybrisJobs = {
  customer: {
    jobs: [
      {
        jobNumber: "A1COR000",
        jobName: "Wilde & Cartwrig",
        searchName: "Wilde & Cartwrig",
        address1: "Wilde & Cartwright",
        address2: "215B Rangi Avenue",
      },
      {
        jobNumber: "A1COR001",
        jobName: "Nathan Douglas",
        searchName: "Nathan Douglas",
        address1: "Nathan Douglas",
        address2: "20 Mataura Road",
      },
      {
        jobNumber: "A1COR002",
        jobName: "Angela & Kevin J",
        searchName: "Angela & Kevin J",
        address1: "Angela & Kevin Jane",
        address2: "LotNo 4",
      },
      {
        jobNumber: "A1COR003",
        jobName: "Home and Bach Construction Limited t/a A1 Homes - Coromandel",
        searchName: "Jane Extra",
        address1: "",
        address2: "",
      },
    ],
  },
};

export const ExpectedHybrisJobs = [
  {
    Address1: "Wilde & Cartwright",
    Address2: "215B Rangi Avenue",
    JobName: "Wilde & Cartwrig",
    JobNumber: "A1COR000",
    SearchName: "Wilde & Cartwrig",
    JobId: "",
  },
  {
    Address1: "Nathan Douglas",
    Address2: "20 Mataura Road",
    JobName: "Nathan Douglas",
    JobNumber: "A1COR001",
    SearchName: "Nathan Douglas",
    JobId: "",
  },
  {
    Address1: "Angela & Kevin Jane",
    Address2: "LotNo 4",
    JobName: "Angela & Kevin J",
    JobNumber: "A1COR002",
    SearchName: "Angela & Kevin J",
    JobId: "",
  },
  {
    Address1: "",
    Address2: "",
    JobName: "Home and Bach Construction Limited t/a A1 Homes - Coromandel",
    JobNumber: "A1COR003",
    SearchName: "Jane Extra",
    JobId: "",
  },
];

export const BranchDetails = {
  address: {
    country: {
      isocode: "NZ",
      name: "New Zealand",
    },
    defaultAddress: false,
    email: "sales.thames@placemakers.co.nz",
    formattedAddress: "P O BOX 510, 73 KOPU RD, Bay of Plenty",
    id: "8796617342999",
    line1: "P O BOX 510",
    line2: "73 KOPU RD",
    phone: "(07)868-0130",
    region: {
      countryIso: "NZ",
      isocode: "NZ-BOP",
      isocodeShort: "BOP",
      name: "Bay of Plenty",
    },
    shippingAddress: false,
    visibleInAddressBook: true,
  },
  branchCode: "362",
  branchID: "P362",
  branchLegalName: "MCGILL BUILDING SUPPLIES LTD",
  branchRegionalCode: "NZ-BOP",
  features: {},
  geoPoint: {
    latitude: -37.18755,
    longitude: 175.566355,
  },
  isActive: true,
  isBranch: true,
  name: "THAMES",
  parentBranchID: "P362",
  storeImages: [],
};

export const SampleCollection = {
  data: {
    jobAccountIds: "ANTGA000, ANTGA001, ANTGA002",
    tradeAccount: {
      accountId: "ANTGA",
      accountName: "Ants General Contracting",
      address: {
        address1: "PO BOX 116",
        address2: "Tairua",
        address3: "",
        address4: "",
        address5: "",
        city: "Tairua",
        suburb: "",
      },
      orders: [
        {
          customerPOReference: "cust test",
          deliveryAddress: {
            address1: "79 KOPU RD",
            address2: "P O BOX 510",
            city: "THAMES",
            suburb: "",
          },
          deliveryDate: "0001-01-01T00:00:00",
          deliveryType: "",
          directShip: "N",
          dsp: "",
          fulfilmentBranchId: "362",
          fulfilmentType: "Pickup",
          linkedInvoice: "",
          orderGSTAmt: "3.57",
          orderLines: [
            {
              description: "GIB STANDARD 2400X1200 10MM WALLBOARD",
              extLineTotalExcl: "0.00",
              gstAmount: "0.00",
              lineNumber: "1",
              qtyOrdered: "1.0000",
              sku: "2800027",
              supplier: {
                supplierName: "",
                supplierPODate: "0001-01-01T00:00:00",
              },
              unitDescription: "SHEET",
              unitOfMeasure: "ST",
              unitPrice: "23.7726",
            },
          ],
          orderNumber: "1415345",
          orderProcessed: {
            branch: "PLACEMAKERS THAMES",
            by: "pmanakat",
            when: "2020-04-14T00:00:00",
          },
          orderStatus: "ORDER CONFIRMED",
          orderTotalExclGST: "23.77",
          packNumber: "",
          pdoNumber: "1415345-1",
          pickupTime: "09:00:00",
          requestDate: "2020-04-17T00:00:00",
          siteContact: [
            {
              email: "prasad.manakattil@fbu.com",
              name: "prasad ",
              phone: "0211859189",
            },
          ],
          stagingAreas: [],
          supplierDirectMessage: "",
          totalOrderLines: "1",
        },
      ],
    },
  },
};

export const OrderData = {
  orderItems: [],
  orderNumber: "1401678-1",
  customerId: "HADAA",
  fulfilmentType: "Pickup",
  status: "PICKING",
  isDsOrder: undefined,
  requestDate: "Nov 5, 2019 12:00 AM",
  pickupTime: "11:00:00",
  delivery: undefined,
  jobDetails: {},
  supplier: [
    {
      SupplierName: "WINSTONE WALLBOARDS LTD",
      SupplierPODate: "2020-02-04T00:00:00",
    },
  ],
  collection: undefined,
  headerDetails: {
    isDelivered: false,
    isEstimated: false,
    DSP: "",
    text: "Collect (includes special items from supplier)",
  },
  siteContact: {},
  original: {},
};
export const HeaderMessage = {
  AccountName: "Aaron Haddon Builders Limited",
  CustomerId: "HADAA",
  AccountId: "HADAA",
  OrderNumber: "1402232",
  PDONumber: "1402232-2",
  RequestDate: "2020-02-13T00:00:00",
  DeliveryDate: "0001-01-01T00:00:00",
  DSP: "",
  fulfilmentType: "Pickup",
  deliveryType: "",
  directShip: "N",
  supplierDirectMessage: "",
  CustomerPOReference: "",
  OrderTotalExclGST: 1046.97,
  OrderGSTAmt: 57.87,
  LinkedInvoice: "1386874",
  TotalOrderLines: 1,
  OrderStatus: "ORDER CONFIRMED",
  StagingAreas: [],
  PickupTime: "11:00:00",
  OrderProcessed: {},
  SiteContact: [],
  DeliveryAddress: {},
  DeliveryRequirements: {},
  orderLines: [],
};
export const OrdersList = [
  {
    AccountName: "Aaron Haddon Builders Limited",
    CustomerId: "HADAA",
    AccountId: "HADAA",
    OrderNumber: "1401678",
    OrderLines: [
      {
        LineNumber: 1,
        Supplier: {
          SupplierName: "WINSTONE WALLBOARDS LTD",
          SupplierPODate: "2019-11-05T00:00:00",
        },
      },
      {
        LineNumber: 2,
        Supplier: {
          SupplierName: "",
          SupplierPODate: "2019-11-05T00:00:00",
        },
      },
    ],
  },
  {
    AccountName: "Aaron Haddon Builders Limited",
    CustomerId: "HADAA",
    AccountId: "HADAA",
    OrderNumber: "1402232",
    OrderLines: [
      {
        LineNumber: 1,
        Supplier: {
          SupplierName: "",
          SupplierPODate: "2019-11-05T00:00:00",
        },
      },
    ],
  },
];
export const OriginalResponse = {
  accountName: "Ants General Contracting",
  customerId: "ANTGA",
  accountId: "ANTGA",
  customerPOReference: "Dsline",
  deliveryAddress: {
    address1: "23/1 Ambrico Place",
    address2: "",
    city: "Auckland",
    suburb: "New Lynn",
  },
  deliveryDate: "0001-01-01T00:00:00",
  deliveryRequirements: { siteRequirements: [] },
  deliveryType: "Standard Delivery",
  directShip: "N",
  dsp: "ANYTIME",
  fulfilmentBranchId: "362",
  fulfilmentType: "Delivery",
  linkedInvoice: "",
  orderGSTAmt: "6.30",
  orderLines: [
    {
      description: "GIB STANDARD 2400X1200 10MM WALLBOARD",
      extLineTotalExcl: "50.00",
      gstAmount: "7.50",
      lineNumber: "1",
      qtyOrdered: "1.0000",
      sku: "2800027",
      supplier: { supplierName: "", supplierPODate: "0001-01-01T00:00:00" },
      unitDescription: "SHEET",
      unitOfMeasure: "ST",
      unitPrice: "10.0000",
    },
    {
      description: "DRICON RAPIDSET 25KG",
      extLineTotalExcl: "12.60",
      gstAmount: "1.89",
      lineNumber: "2",
      qtyOrdered: "1.0000",
      sku: "3250974",
      supplier: { supplierName: "", supplierPODate: "2020-10-22T00:00:00" },
      unitDescription: "BAG",
      unitOfMeasure: "BG",
      unitPrice: "12.6000",
    },
    {
      description: "DRICON PAVELOCK 20KG",
      extLineTotalExcl: "19.39",
      gstAmount: "2.91",
      lineNumber: "3",
      qtyOrdered: "1.0000",
      sku: "3251950",
      supplier: { supplierName: "", supplierPODate: "2020-10-22T00:00:00" },
      unitDescription: "BAG",
      unitOfMeasure: "BG",
      unitPrice: "19.3903",
    },
  ],
  orderNumber: "1416867",
  orderProcessed: {
    branch: "PLACEMAKERS THAMES",
    by: "pmanakat",
    when: "2020-10-22T00:00:00",
  },
  orderStatus: "ORDER CONFIRMED",
  orderTotalExclGST: "41.99",
  packNumber: "",
  pdoNumber: "1416867-1",
  pickupTime: "00:00:00",
  requestDate: "2020-10-30T00:00:00",
  siteContact: [{ email: "", name: "Jas Test", phone: "0222647344" }],
  stagingAreas: [],
  supplierDirectMessage: "Delivery (Direct from Supplier)",
  totalOrderLines: "3",
};

export const OrderJson = {
  nav: {},
  login: {},
  orderDeliveries: {},
  product: {},
  orderDetails: {},
  address: {},
  orderJourney: {},
  jobAccounts: {
    fetching: false,
    error: false,
    data: [
      {
        JobNumber: "A1COR000",
        JobName: "Wilde & Cartwrig",
        SearchName: "Wilde & Cartwrig",
        Address1: "Wilde & Cartwright",
        Address2: "215B Rangi Avenue",
      },
      {
        JobNumber: "A1COR001",
        JobName: "Nathan Douglas",
        SearchName: "Nathan Douglas",
        Address1: "Nathan Douglas",
        Address2: "20 Mataura Road",
      },
      {
        JobNumber: "A1COR002",
        JobName: "Angela & Kevin J",
        SearchName: "Angela & Kevin J",
        Address1: "Angela & Kevin Jane",
        Address2: "LotNo 4",
      },
      {
        JobNumber: "A1COR003",
        JobName: "Home and Bach Construction Limited t/a A1 Homes - Coromandel",
        SearchName: "Jane Extra",
        Address1: "",
        Address2: "",
      },
    ],
  },
  email: {},
  permission: {},
  manageTeam: {},
  marketingScreens: {},
  countryList: {},
  signUp: {},
  branchList: {
    data: [],
    dataDepots: [
      {
        address: {
          country: {
            isocode: "NZ",
            name: "New Zealand",
          },
          defaultAddress: false,
          email: "sales.thames@placemakers.co.nz",
          formattedAddress: "P O BOX 510, 73 KOPU RD, Bay of Plenty",
          id: "8796617342999",
          line1: "P O BOX 510",
          line2: "73 KOPU RD",
          phone: "(07)868-0130",
          region: {
            countryIso: "NZ",
            isocode: "NZ-BOP",
            isocodeShort: "BOP",
            name: "Bay of Plenty",
          },
          shippingAddress: false,
          visibleInAddressBook: true,
        },
        branchCode: "362",
        branchID: "P362",
        branchLegalName: "MCGILL BUILDING SUPPLIES LTD",
        branchRegionalCode: "NZ-BOP",
        features: {},
        geoPoint: {
          latitude: -37.18755,
          longitude: 175.566355,
        },
        isActive: true,
        isBranch: true,
        name: "THAMES",
        parentBranchID: "P362",
        storeImages: [],
      },
    ],
    fetching: false,
    selectedBranch: {},
    selectedOrderType: "Courier",
    branchDetailError: false,
    branchDetails: {},
  },
  editPermission: {},
  connectTrade: {},
  search: {},
  searchList: {},
  appDetail: {},
};

export const GetPermissionResponse = {
  accountID: "584481",
  customerID: "rajeev.gvs@royalcyber.com",
  endDate: "2019-12-11T11:00:00+0000",
  creditLimit: 1000,
  permissionList: [
    {
      name: "B2B Admin Group",
      uid: "accountAdminGroup",
    },
    {
      name: "View Orders group",
      uid: "viewOrderGroup",
    },
    {
      name: "Restrict Price Group",
      uid: "restrictPriceGroup",
    },
    {
      name: "Place Order User Group",
      uid: "placeOrderGroup",
    },
  ],
  startDate: "2018-11-11T11:00:00+0000",
  temporaryAccess: true,
};

export const DeliveryDetails = {
  value: {
    nav: {},
    login: {},
    orderDeliveries: {},
    product: {},
    orderDetails: {},
    address: {},
    email: {},
    permission: {},
    manageTeam: {},
    marketingScreens: {},
    countryList: {},
    signUp: {},
    branchList: {
      data: [{}],
      fetching: true,
      selectedBranch: {},
      selectedOrderType: "Picker",
      branchDetailError: false,
      skipped: false,
      branchDetails: {},
      fetchingBranchDetails: false,
    },
    editPermission: {},
    connectTrade: {},
    search: {},
    searchList: {},
    appDetail: {},
  },
};

export const PricingDetails = {
  entries: [
    {
      availableForPickup: true,
      basePrice: {
        currencyIso: "NZD",
        formattedValue: "$10.00",
        priceType: "BUY",
        value: 10,
      },
      configurationInfos: [],
      decimalQty: 2,
      deliveryOrder: true,
      entryNumber: 0,
      product: {
        availableForPickup: true,
        baseOptions: [],
        categories: [
          {
            code: "BC11QA",
            name: "Standard 10Mm",
            url: "/Building-Products/Plasterboard/Standard-Board/Standard-10Mm/c/BC11QA",
          },
        ],
        code: "2800027",
        configurable: false,
        description:
          "The GIB Standard Wallboard is suitable for interior lining in internal walls. It measures 2400 mm x 1200 mm x 10 mm. The gypsum construction makes this product a stronger and more flexible. This wallboard is ideal for ceilings as it is less prone to sagging than other plasterboard. The enhanced manoeuvrability minimizes risk of damage and wastage. Strengthened yellow face paper ensures a consistent surface finish- Test@ t e!@#$%^&*()_+testdesc2",
        expressOrder: true,
        hasNoQuantity: 0,
        images: [
          {
            altText: "GIB|Standard Wallboard|2400 x 1200 x 10 mm Yellow Face Paper Gypsum|11535",
            format: "zoom",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012050_GIB_11535.jpg",
          },
          {
            altText: "GIB|Standard Wallboard|2400 x 1200 x 10 mm Yellow Face Paper Gypsum|11535",
            format: "product",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012050_GIB_11535.jpg",
          },
          {
            altText: "GIB|Standard Wallboard|2400 x 1200 x 10 mm Yellow Face Paper Gypsum|11535",
            format: "thumbnail",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012050_GIB_11535.jpg",
          },
          {
            altText: "GIB|Standard Wallboard|2400 x 1200 x 10 mm Yellow Face Paper Gypsum|11535",
            format: "cartIcon",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012050_GIB_11535.jpg",
          },
        ],
        manufacturer: "GIB-Test1",
        name: "GIB|Standard Wallboard|2400 x 1200 x 10 mm Yellow Face Paper Gypsum|11535",
        price: {
          currencyIso: "NZD",
          formattedValue: "$10.00",
          priceType: "BUY",
          value: 10,
        },
        purchasable: true,
        sellOrderMultiple: 0,
        stock: {
          pmStockQuantity: "816",
          statusCode: "1",
          stockLevelStatus: "inStock",
        },
        timberProductFlag: true,
        unitCode: "ST",
        uomFormat: "5",
        url: "/Building-Products/Plasterboard/Standard-Board/Standard-10Mm/GIB%7CStandard-Wallboard%7C2400-x-1200-x-10-mm-Yellow-Face-Paper-Gypsum%7C11535/p/2800027",
      },
      quantity: 1,
      totalPrice: {
        currencyIso: "NZD",
        formattedValue: "$20.00",
        priceType: "BUY",
        value: 20,
      },
      unit: "ST",
      updateable: true,
    },
    {
      availableForPickup: true,
      basePrice: {
        currencyIso: "NZD",
        formattedValue: "$78.24",
        priceType: "BUY",
        value: 78.24,
      },
      configurationInfos: [],
      decimalQty: 1,
      deliveryOrder: true,
      entryNumber: 1,
      product: {
        availableForPickup: true,
        baseOptions: [],
        categories: [
          {
            code: "CC18AH",
            name: "Loose Nails Roofing",
            url: "/Fastenings-%26-General-Hardware/Fastenings/Loose-Nails/Loose-Nails-Roofing/c/CC18AH",
          },
        ],
        code: "3537578",
        configurable: false,
        description:
          "The Bremick NU-FIX Roofing Nail in grey colour, is suitable for fixing various profiles in galvanised roofing iron. This nail measuring 4 mm x 75 mm, features bullet head that offers great versatility. Nail with spiral shaft, features steel construction and hot-dipped galvanized finish that offers excellent resistance to corrosion.",
        expressOrder: true,
        hasNoQuantity: 0,
        images: [
          {
            altText: "NZ Nails NU-FIX Roofing Nail 4 x 75mm Dome Head with Washer Hot Dip Galvanised 075400GNH",
            format: "zoom",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
          },
          {
            altText: "NZ Nails NU-FIX Roofing Nail 4 x 75mm Dome Head with Washer Hot Dip Galvanised 075400GNH",
            format: "product",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
          },
          {
            altText: "NZ Nails NU-FIX Roofing Nail 4 x 75mm Dome Head with Washer Hot Dip Galvanised 075400GNH",
            format: "thumbnail",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
          },
          {
            altText: "NZ Nails NU-FIX Roofing Nail 4 x 75mm Dome Head with Washer Hot Dip Galvanised 075400GNH",
            format: "cartIcon",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/NZ_Nails_075400GNH.jpg",
          },
        ],
        manufacturer: "NZ NAILS",
        name: "NZ Nails NU-FIX Roofing Nail 4 x 75mm Dome Head with Washer Hot Dip Galvanised 075400GNH",
        price: {
          currencyIso: "NZD",
          formattedValue: "$78.24",
          priceType: "BUY",
          value: 78.24,
        },
        purchasable: true,
        stock: {
          pmStockQuantity: "5",
          statusCode: "1",
          stockLevelStatus: "inStock",
        },
        timberProductFlag: false,
        unitCode: "PA",
        uomFormat: "5",
        url: "/Fastenings-%26-General-Hardware/Fastenings/Loose-Nails/Loose-Nails-Roofing/NZ-Nails-NU-FIX-Roofing-Nail-4-x-75mm-Dome-Head-with-Washer-Hot-Dip-Galvanised-075400GNH/p/3537578",
      },
      quantity: 1,
      totalPrice: {
        currencyIso: "NZD",
        formattedValue: "$78.24",
        priceType: "BUY",
        value: 78.24,
      },
      unit: "PA",
      updateable: true,
    },
  ],
};

export const LoginData = {
  aud: "UB6hCkWjKKC58qgqilkfoVaD9ID4vmEN",
  email: "shashika.abeysuriya@fbu.com",
  email_verified: false,
  exp: 1608572386,
  family_name: "Abeysuriya",
  given_name: "shashika",
  "https://ecommerce.placemakers.co.nz/email": "shashika.abeysuriya@fbu.com",
  "https://ecommerce.placemakers.co.nz/firstName": "shashika",
  "https://ecommerce.placemakers.co.nz/fromSignup": false,
  "https://ecommerce.placemakers.co.nz/phoneNumber": "+64272542871",
  "https://ecommerce.placemakers.co.nz/surname": "Abeysuriya",
  "https://ecommerce.placemakers.co.nz/tradeAccounts": {
    tradeAccounts: [
      {
        branchCode: "362",
        custId: "BLAK2",
        uid: "362BLAK2",
      },
      {
        branchCode: "362",
        custId: "BLAK1",
        uid: "362BLAK1",
      },
      {
        branchCode: "405",
        custId: "ZEDCA",
        uid: "405ZEDCA",
      },
      {
        branchCode: "473",
        custId: "ZEDCA",
        uid: "473ZEDCA",
      },
      {
        branchCode: "481",
        custId: "ZEDCA",
        uid: "481ZEDCA",
      },
      {
        branchCode: "473",
        custId: "LSFIX",
        uid: "473LSFIX",
      },
      {
        branchCode: "362",
        custId: "LTFIX",
        uid: "362LTFIX",
      },
      {
        branchCode: "473",
        custId: "LTFIX",
        uid: "473LTFIX",
      },
      {
        branchCode: "545",
        custId: "ARMWA",
        uid: "545ARMWA",
      },
      {
        branchCode: "362",
        custId: "UATT1",
        uid: "362UATT1",
      },
      {
        branchCode: "362",
        custId: "ADBAB",
        uid: "362ADBAB",
      },
      {
        branchCode: "367",
        custId: "2BUIL",
        uid: "3672BUIL",
      },
      {
        branchCode: "473",
        custId: "TESTE",
        uid: "473TESTE",
      },
      {
        branchCode: "362",
        custId: "TESTE",
        uid: "362TESTE",
      },
      {
        branchCode: "367",
        custId: "MINHA",
        uid: "367MINHA",
      },
    ],
  },
  iat: 1608536386,
  iss: "https://uat-auth.placemakers.co.nz/",
  name: "shashika.abeysuriya@fbu.com",
  nickname: "shashika.abeysuriya",
  picture: "https://s.gravatar.com/avatar/08ad3389d5978ef528dfdf2bf08bbc8d?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fsh.png",
  sub: "auth0|5fb1b9056dd905006f719129",
  updated_at: "2020-12-21T07:37:35.727Z",
};

export const TradeAccountData = {
  cimSubscriberKey: "5fb1b9056dd905006f719129",
  companies: [
    {
      addresses: [
        {
          id: "8802319138839",
        },
      ],
      name: "Blake Johnson1 Industries",
      tradeAccounts: [],
      uid: "CIM-248774",
    },
    {
      addresses: [
        {
          id: "8798409850903",
        },
      ],
      name: "ZEDESS CONSTRUCTION LIMITED",
      tradeAccounts: [
        {
          branch: {
            branchCode: "473",
            branchID: "P473",
            branchLegalName: "Placemakers Westgate",
            name: "Westgate",
          },
          custId: "ZEDCA",
          masterOnHold: true,
          name: "Zedess Construction Limited",
          uid: "473ZEDCA",
        },
        {
          branch: {
            branchCode: "481",
            branchID: "P481",
            branchLegalName: "Placemakers Cook Street",
            name: "Cook St",
          },
          custId: "ZEDCA",
          masterOnHold: false,
          name: "Zedess Construction Limited",
          uid: "481ZEDCA",
        },
      ],
      uid: "CIM-14470",
    },
    {
      addresses: [
        {
          id: "8802286206999",
        },
      ],
      name: "Latest Fix Ltd.",
      tradeAccounts: [
        {
          branch: {
            branchCode: "473",
            branchID: "P473",
            branchLegalName: "Placemakers Westgate",
            name: "Westgate",
          },
          custId: "LSFIX",
          masterOnHold: false,
          name: "Latest Fix Ltd.",
          uid: "473LSFIX",
        },
        {
          branch: {
            branchCode: "473",
            branchID: "P473",
            branchLegalName: "Placemakers Westgate",
            name: "Westgate",
          },
          custId: "LTFIX",
          masterOnHold: false,
          name: "Latest Fix Ltd.",
          uid: "473LTFIX",
        },
      ],
      uid: "CIM-248765",
    },
    {
      addresses: [
        {
          id: "8798284185623",
        },
      ],
      name: "ARMITAGE WILLIAMS CONSTRUCTION LIMITED",
      tradeAccounts: [
        {
          branch: {
            branchCode: "545",
            branchID: "P545",
            branchLegalName: "Placemakers Christchurch Limited",
            name: "Christchurch Hub",
          },
          custId: "ARMWA",
          masterOnHold: false,
          name: "Armitage Williams Construction Ltd",
          uid: "545ARMWA",
        },
      ],
      uid: "CIM-58143",
    },
    {
      addresses: [
        {
          id: "8807889534999",
        },
      ],
      name: "UAT TEST LTD",
      tradeAccounts: [
        {
          branch: {
            branchCode: "362",
            branchID: "P362",
            branchLegalName: "Mcgill Building Supplies Ltd",
            name: "Thames",
          },
          custId: "UATT1",
          masterOnHold: false,
          name: "Uat Test Ltd",
          uid: "362UATT1",
        },
      ],
      uid: "CIM-252549",
    },
    {
      name: "Hybris Company",
      tradeAccounts: [
        {
          branch: {
            branchCode: "362",
            branchID: "P362",
            branchLegalName: "Mcgill Building Supplies Ltd",
            name: "Thames",
          },
          custId: "ADBAB",
          masterOnHold: false,
          name: "A & D Builders",
          uid: "362ADBAB",
        },
      ],
      uid: "HYB015002",
    },
    {
      addresses: [
        {
          id: "8798749523991",
        },
      ],
      name: "2 BUILD LIMITED",
      uid: "CIM-08958",
    },
    {
      addresses: [
        {
          id: "8802024161303",
        },
      ],
      name: "NewUserThree Limited",
      tradeAccounts: [
        {
          branch: {
            branchCode: "473",
            branchID: "P473",
            branchLegalName: "Placemakers Westgate",
            name: "Westgate",
          },
          custId: "TESTE",
          masterOnHold: false,
          name: "Newuserthree Limited",
          uid: "473TESTE",
        },
      ],
      uid: "CIM-248725",
    },
    {
      name: "A  Minhas",
      tradeAccounts: [
        {
          branch: {
            branchCode: "367",
            branchID: "P367",
            branchLegalName: "Fletcher Distribution Limited",
            name: "Clarence Street Hamilton",
          },
          custId: "MINHA",
          masterOnHold: false,
          name: "A  Minhas",
          uid: "367MINHA",
        },
      ],
      uid: "CIM-60776",
    },
  ],
  currency: {
    active: false,
    isocode: "NZD",
    name: "New Zeland Dollar",
    symbol: "$",
  },
  displayUid: "shashika.abeysuriya@fbu.com",
  isLicenseUpdated: true,
  mobileNumber: "64272542871",
  name: "shashika",
  roles: ["b2bcustomergroup"],
  type: "userWsDTO",
  uid: "shashika.abeysuriya@fbu.com",
};

export const ExpectedTradeAccount = {
  branch: {
    branchCode: "473",
    branchID: "P473",
    branchLegalName: "Placemakers Westgate",
    name: "Westgate",
  },
  custId: "ZEDCA",
  masterOnHold: true,
  name: "Zedess Construction Limited",
  uid: "473ZEDCA",
};

export const BranchDataArr = [
  {
    statusArr: ["Open", "#02B382", "5:30 PM"],
    address: {
      country: { isocode: "NZ", name: "New Zealand" },
      defaultAddress: false,
      email: "angelin.nayagam@royalcyber.com",
      formattedAddress: "P O BOX 100 241, 3 LINK DR, Auckland",
      id: "8796093120535",
      line1: "P O BOX 100 241",
      line2: "3 LINK DR",
      phone: "(09)444-5155",
      region: {
        countryIso: "NZ",
        isocode: "NZ-AKL",
        isocodeShort: "AKL",
        name: "Auckland",
      },
      shippingAddress: false,
      town: "Auckland",
      visibleInAddressBook: true,
    },
    branchCode: "471",
    branchID: "P471",
    branchLegalName: "STEVEN MARSHALL BUILDING SUPPLIES LTD",
    branchRegionalCode: "NZ-AKL",
    features: {},
    formattedDistance: "5.3 Km",
    geoPoint: { latitude: -36.7687735, longitude: 174.73815926 },
    isActive: true,
    isBranch: true,
    name: "Wairau Park",
    openingHours: {
      code: "471-Working Hours",
      specialDayOpeningList: [],
      weekDayOpeningList: [
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Mon",
        },
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Tue",
        },
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Wed",
        },
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Thu",
        },
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Fri",
        },
        {
          closingTime: { formattedHour: "17:00", hour: 5, minute: 0 },
          openingTime: { formattedHour: "07:30", hour: 7, minute: 30 },
          closed: false,
          weekDay: "Sat",
        },
        {
          closingTime: { formattedHour: "17:00", hour: 5, minute: 0 },
          openingTime: { formattedHour: "09:00", hour: 9, minute: 0 },
          closed: false,
          weekDay: "Sun",
        },
      ],
    },
    parentBranchID: "P471",
    storeImages: [],
    url: "/store/Wairau Park?lat=-36.803304&long=174.697899",
  },
];

export const ExpectedBranchDataArr = [
  {
    statusArr: ["Open", "#02B382", "5:30 PM"],
    branchName: "Wairau Park",
    branchAddress: "P O BOX 100 241, 3 LINK DR, Auckland",
    branchDistance: "5.3 Km",
    address: {
      country: { isocode: "NZ", name: "New Zealand" },
      defaultAddress: false,
      email: "angelin.nayagam@royalcyber.com",
      formattedAddress: "P O BOX 100 241, 3 LINK DR, Auckland",
      id: "8796093120535",
      line1: "P O BOX 100 241",
      line2: "3 LINK DR",
      phone: "(09)444-5155",
      region: {
        countryIso: "NZ",
        isocode: "NZ-AKL",
        isocodeShort: "AKL",
        name: "Auckland",
      },
      shippingAddress: false,
      town: "Auckland",
      visibleInAddressBook: true,
    },
    branchCode: "471",
    branchID: "P471",
    branchLegalName: "STEVEN MARSHALL BUILDING SUPPLIES LTD",
    branchRegionalCode: "NZ-AKL",
    features: {},
    formattedDistance: "5.3 Km",
    geoPoint: { latitude: -36.7687735, longitude: 174.73815926 },
    isActive: true,
    isBranch: true,
    name: "Wairau Park",
    openingHours: {
      code: "471-Working Hours",
      specialDayOpeningList: [],
      weekDayOpeningList: [
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Mon",
        },
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Tue",
        },
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Wed",
        },
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Thu",
        },
        {
          closingTime: { formattedHour: "17:30", hour: 5, minute: 30 },
          openingTime: { formattedHour: "07:00", hour: 7, minute: 0 },
          closed: false,
          weekDay: "Fri",
        },
        {
          closingTime: { formattedHour: "17:00", hour: 5, minute: 0 },
          openingTime: { formattedHour: "07:30", hour: 7, minute: 30 },
          closed: false,
          weekDay: "Sat",
        },
        {
          closingTime: { formattedHour: "17:00", hour: 5, minute: 0 },
          openingTime: { formattedHour: "09:00", hour: 9, minute: 0 },
          closed: false,
          weekDay: "Sun",
        },
      ],
    },
    parentBranchID: "P471",
    storeImages: [],
    url: "/store/Wairau Park?lat=-36.803304&long=174.697899",
  },
];

export const ExpectedHoursObj = {
  closed: false,
  closingTime: {
    formattedHour: "17:30",
    hour: 5,
    minute: 30,
  },
  openingTime: {
    formattedHour: "07:00",
    hour: 7,
    minute: 0,
  },
  weekDay: "Wed",
};

export const ExpectedJobAccountsArr = [
  {
    accountId: "ADITA000",
    accountName: "Andrews Job0",
    address: {
      address1: "PO BOX 262",
      address2: "Thames",
      address3: "",
      address4: "",
      address5: "",
      city: "Thames",
      suburb: "",
    },
    orders: [
      {
        customerPOReference: "Prasad- jobaccount",
        deliveryAddress: {
          address1: "79 KOPU RD",
          address2: "P O BOX 510",
          city: "THAMES",
          suburb: "",
        },
        deliveryDate: "0001-01-01T00:00:00",
        deliveryRequirements: {
          siteRequirements: [],
        },
        deliveryType: "",
        directShip: "N",
        dsp: "",
        fulfilmentType: "Pickup",
        linkedInvoice: "",
        orderGSTAmt: "37.52",
        orderLines: [
          {
            description: "GIB STANDARD 2400X1200 10MM WALLBOARD",
            extLineTotalExcl: "20.85",
            gstAmount: "3.13",
            lineNumber: "1",
            qtyOrdered: "12.0000",
            sku: "2800027",
            supplier: {
              supplierName: "",
              supplierPODate: "0001-01-01T00:00:00",
            },
            unitDescription: "SHEET",
            unitOfMeasure: "ST",
            unitPrice: "20.8450",
          },
        ],
        orderNumber: "1416630",
        orderProcessed: {
          branch: "PLACEMAKERS THAMES",
          by: "pmanakat",
          when: "2020-09-29T00:00:00",
        },
        orderStatus: "ORDER CONFIRMED",
        orderTotalExclGST: "250.14",
        pdoNumber: "1416630-1",
        pickupTime: "00:00:00",
        requestDate: "2020-09-29T00:00:00",
        siteContact: [],
        stagingAreas: [],
        supplierDirectMessage: "",
        totalOrderLines: "1",
      },
      {
        customerPOReference: "PrasadParent order",
        deliveryAddress: {
          address1: "79 KOPU RD",
          address2: "P O BOX 510",
          city: "THAMES",
          suburb: "",
        },
        deliveryDate: "0001-01-01T00:00:00",
        deliveryRequirements: {
          siteRequirements: [],
        },
        deliveryType: "",
        directShip: "N",
        dsp: "",
        fulfilmentType: "Pickup",
        linkedInvoice: "",
        orderGSTAmt: "0.69",
        orderLines: [
          {
            description: "100 X 50 (90X45) RAD SG8 H1.2 PG KD 4.8",
            extLineTotalExcl: "55.20",
            gstAmount: "8.28",
            lineNumber: "1",
            qtyOrdered: "1.0000",
            sku: "1015258",
            supplier: {
              supplierName: "",
              supplierPODate: "0001-01-01T00:00:00",
            },
            unitDescription: "LINEAL METRE",
            unitOfMeasure: "LM",
            unitPrice: "4.6000",
          },
        ],
        orderNumber: "1416632",
        orderProcessed: {
          branch: "PLACEMAKERS THAMES",
          by: "root",
          when: "2020-09-29T00:00:00",
        },
        orderStatus: "ORDER CONFIRMED",
        orderTotalExclGST: "4.60",
        pdoNumber: "1416632-1",
        pickupTime: "15:00:00",
        requestDate: "2020-09-29T00:00:00",
        siteContact: [
          {
            email: "prasad.manakattil@fbu.com",
            name: "prasad manakattil manakattil",
            phone: "0211859189",
          },
        ],
        stagingAreas: [],
        supplierDirectMessage: "",
        totalOrderLines: "1",
      },
    ],
  },
];

export const ExpectedCombinedOrdersArr = [
  {
    customerPOReference: "Prasad- jobaccount",
    deliveryAddress: {
      address1: "79 KOPU RD",
      address2: "P O BOX 510",
      city: "THAMES",
      suburb: "",
    },
    deliveryDate: "0001-01-01T00:00:00",
    deliveryRequirements: {
      siteRequirements: [],
    },
    deliveryType: "",
    directShip: "N",
    dsp: "",
    fulfilmentType: "Pickup",
    linkedInvoice: "",
    orderGSTAmt: "37.52",
    orderLines: [
      {
        description: "GIB STANDARD 2400X1200 10MM WALLBOARD",
        extLineTotalExcl: "20.85",
        gstAmount: "3.13",
        lineNumber: "1",
        qtyOrdered: "12.0000",
        sku: "2800027",
        supplier: {
          supplierName: "",
          supplierPODate: "0001-01-01T00:00:00",
        },
        unitDescription: "SHEET",
        unitOfMeasure: "ST",
        unitPrice: "20.8450",
      },
    ],
    orderNumber: "1416630",
    orderProcessed: {
      branch: "PLACEMAKERS THAMES",
      by: "pmanakat",
      when: "2020-09-29T00:00:00",
    },
    orderStatus: "ORDER CONFIRMED",
    orderTotalExclGST: "250.14",
    pdoNumber: "1416630-1",
    pickupTime: "00:00:00",
    requestDate: "2020-09-29T00:00:00",
    siteContact: [],
    stagingAreas: [],
    supplierDirectMessage: "",
    totalOrderLines: "1",
  },
  {
    customerPOReference: "PrasadParent order",
    deliveryAddress: {
      address1: "79 KOPU RD",
      address2: "P O BOX 510",
      city: "THAMES",
      suburb: "",
    },
    deliveryDate: "0001-01-01T00:00:00",
    deliveryRequirements: {
      siteRequirements: [],
    },
    deliveryType: "",
    directShip: "N",
    dsp: "",
    fulfilmentType: "Pickup",
    linkedInvoice: "",
    orderGSTAmt: "0.69",
    orderLines: [
      {
        description: "100 X 50 (90X45) RAD SG8 H1.2 PG KD 4.8",
        extLineTotalExcl: "55.20",
        gstAmount: "8.28",
        lineNumber: "1",
        qtyOrdered: "1.0000",
        sku: "1015258",
        supplier: {
          supplierName: "",
          supplierPODate: "0001-01-01T00:00:00",
        },
        unitDescription: "LINEAL METRE",
        unitOfMeasure: "LM",
        unitPrice: "4.6000",
      },
    ],
    orderNumber: "1416632",
    orderProcessed: {
      branch: "PLACEMAKERS THAMES",
      by: "root",
      when: "2020-09-29T00:00:00",
    },
    orderStatus: "ORDER CONFIRMED",
    orderTotalExclGST: "4.60",
    pdoNumber: "1416632-1",
    pickupTime: "15:00:00",
    requestDate: "2020-09-29T00:00:00",
    siteContact: [
      {
        email: "prasad.manakattil@fbu.com",
        name: "prasad manakattil manakattil",
        phone: "0211859189",
      },
    ],
    stagingAreas: [],
    supplierDirectMessage: "",
    totalOrderLines: "1",
  },
];

export const expectedCartItem_SOM = {
  UniqueId: "1015262-6",
  Brand: "",
  Quantity: "1",
  SKU: "1015262",
  ProductDescription: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
  UOM: "LM",
  Price: "4.60",
  Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1015022.jpg",
  IsTimberProduct: true,
  SelectedMultiple: "6",
  uomFormat: "7.2",
  sellOrderMultiple: "6",
  timberProductFlag: true,
  StockQuantity: "4149",
  IsExpressOrder: false,
  index: 1,
  Availability: "Available",
};

export const expectedCartItem_SOM_zero = {
  UniqueId: "1015262-6",
  Brand: "",
  Quantity: "2",
  SKU: "1015262",
  ProductDescription: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
  UOM: "LM",
  Price: "2.60",
  Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1015022.jpg",
  IsTimberProduct: true,
  SelectedMultiple: "0",
  uomFormat: "7.2",
  sellOrderMultiple: "0",
  timberProductFlag: true,
  StockQuantity: "4149",
  IsExpressOrder: false,
  index: 1,
  Availability: "Available",
};

export const expectedCartItemAllZero = {
  UniqueId: "1015262-6",
  Brand: "",
  Quantity: "3",
  SKU: "1015262",
  ProductDescription: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
  UOM: "LM",
  Price: "5.60",
  Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1015022.jpg",
  IsTimberProduct: false,
  SelectedMultiple: "0",
  uomFormat: "7.2",
  sellOrderMultiple: "0",
  timberProductFlag: true,
  StockQuantity: "4149",
  IsExpressOrder: false,
  index: 1,
  Availability: "Available",
};

export const expectedProductItem = [
  {
    type: "pmProductWsDTO",
    availableForPickup: false,
    barcodesPM: "9414804020224",
    baseOptions: [],
    categories: [
      {
        code: "BU15GB",
        name: "Fast Set",
      },
    ],
    classifications: [
      {
        code: "Specification",
        features: [
          {
            code: "Weight",
            comparable: false,
            featureUnit: {
              name: "Kilogram",
              symbol: "KGM",
              unitType: "KGM",
            },
            featureValues: [
              {
                value: "0.824",
              },
            ],
            name: "Weight",
            range: false,
          },
        ],
        name: "Specifications",
      },
    ],
    code: "3250974",
    configurable: false,
    description:
      "The Firth Dricon Rapidset 25 kg Concrete Bag is designed to use on deck posts and fence posts. Pre-mixed concrete bag consists of special additives that cures the concrete set in just 15 minutes. The setting time is fast in warm conditions and slow in cold conditions.",
    expressOrder: true,
    hasNoQuantity: 25,
    images: [
      {
        format: "zoom",
        imageType: "PRIMARY",
        url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Firth_RS25.jpg",
      },
    ],
    kitProductFlag: false,
    manufacturer: "DRICON",
    name: "Firth Dricon Rapidset General Purpose Concrete Bag 25 kg Grey Powder RS25",
    numberOfReviews: 0,
    perpetualFlag: false,
    price: {
      currencyIso: "NZD",
      formattedValue: "$12.22",
      priceType: "BUY",
      value: 12.22,
    },
    priceRange: {},
    productTypeCodeEnum: "N",
    purchasable: true,
    sellOrderMultiple: 0,
    stock: {
      pmStockQuantity: "422",
      statusCode: "1",
      stockLevelStatus: "inStock",
    },
    summary: "",
    timberProductFlag: false,
    unitCode: "BG",
    uomFormat: "11",
    warrantySheet:
      "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Firth Dricon Bagging July 2016 - Applied Warranty - Building Product Warranty v2.pdf",
  },
];

export const NotitficationsArr = [
  {
    id: "Mzc3OjExNDowOldQdEhxTThLU0VlZS1ScmlXZk01OWc",
    sendDateUtc: "2021-09-10T10:05:00+0500",
    statusDirty: 1,
    alert: "Testing SIT Message",
    messageDeleted: 0,
    subject: "Testing 1340",
    title: "Testing SIT Issue",
    subtitle: "Testing 11 Subtitle",
    startDateUtc: "2021-04-08T22:50:00+0500",
    keys: {
      FBranchID: "362",
      NotifyType: "ORDER_DETAIL",
      BranchID: "362",
      PDONumber: "1417731",
      OrderNumber: "1417731",
      JobAccountID: "ANTGA",
      TradeAccountID: "ANTGA",
    },
    read: 1,
    sound: "default",
    contentType: 2,
    url: "https://fe29117171640474731376.pub.s11.sfmc-content.com/uj0x25xqvwf",
    endDateUtc: "2021-10-01T22:50:00+0500",
    requestId: "a847fb58-0acf-4748-9ef9-1ae259f339f6",
    deleted: 0,
    messageHash: "8LZaWp1Vg2+X0azCi5P8vgAAAAAA",
    name: "",
    date: "10 September",
    dateAndTime: "10:05 AM",
  },
];

export const SampleNotificationExpectObject = [
  {
    title: "10 September",
    data: [
      {
        id: "Mzc3OjExNDowOldQdEhxTThLU0VlZS1ScmlXZk01OWc",
        sendDateUtc: "2021-09-10T10:05:00+0500",
        statusDirty: 1,
        alert: "Testing SIT Message",
        messageDeleted: 0,
        subject: "Testing 1340",
        title: "Testing SIT Issue",
        subtitle: "Testing 11 Subtitle",
        startDateUtc: "2021-04-08T22:50:00+0500",
        keys: {
          FBranchID: "362",
          NotifyType: "ORDER_DETAIL",
          BranchID: "362",
          PDONumber: "1417731",
          OrderNumber: "1417731",
          JobAccountID: "ANTGA",
          TradeAccountID: "ANTGA",
        },
        read: 1,
        sound: "default",
        contentType: 2,
        url: "https://fe29117171640474731376.pub.s11.sfmc-content.com/uj0x25xqvwf",
        endDateUtc: "2021-10-01T22:50:00+0500",
        requestId: "a847fb58-0acf-4748-9ef9-1ae259f339f6",
        deleted: 0,
        messageHash: "8LZaWp1Vg2+X0azCi5P8vgAAAAAA",
        name: "",
        date: "10 September",
        dateAndTime: "10:05 AM",
      },
    ],
  },
];

export const expectedStep1FeatureFlowEventObj = {
  event: "feature_flow",
  feature_type: "STC",
  step: 1,
  location: "",
  device_type: Platform.OS,
  userId: "",
  accountId: "",
  storeName: "",
};

export const expectedStep1BeginCheckoutEventObj = {
  event: "begin_checkout",
  feature_type: "STC",
  step: 2,
  location: "",
  device_type: Platform.OS,
  userId: "",
  accountId: "",
  last_screen: "Dashboard",
  parent_branch: "",
  jobReference: "",
  fulfillment_branch: "",
  order_id: "",
  suspended_id: "",
  storeName: "",
};

export const expectedStep2QrCodeEventObj = {
  event: "begin_checkout",
  feature_type: "stc",
  step: 3,
  location: "",
  device_type: Platform.OS,
  jobReference: "",
  parent_branch: "",
  fulfillment_branch: "",
  userId: "",
  accountId: "",
  order_id: "",
  suspended_id: "",
  addedUsing: "Skip The Counter",
  stcFlowCount: 1,
  storeName: "",
};

export const expectedStep3InProgressEventObj = {
  event: "begin_checkout",
  step: 4,
  location: "",
  device_type: Platform.OS,
  jobReference: "",
  parent_branch: "",
  fulfillment_branch: "",
  userId: "",
  accountId: "",
  feature_type: "STC",
  order_id: "",
  suspended_id: "",
  addedUsing: "Skip The Counter",
  stcFlowCount: 1,
  storeName: "",
};

export const expectedStep4ReviewEventObj = {
  event: "feature_flow",
  feature_type: "STC",
  step: 5,
  location: "",
  device_type: Platform.OS,
  userId: "",
  accountId: "",
  storeName: "",
};

export const expectedStep4ReviewItemsEventObj = {
  event: "begin_checkout",
  step: 6,
  location: "",
  device_type: Platform.OS,
  jobReference: "",
  parent_branch: "",
  fulfillment_branch: "",
  userId: "",
  accountId: "",
  order_id: "",
  suspended_id: "",
  stcFlowCount: 1,
  feature_type: "stc",
  items: [],
  addedUsing: "Skip The Counter",
  storeName: "",
};

export const expectedStep5GatePassEventObj = {
  event: "purchase",
  step: 7,
  feature_type: "STC",
  location: "",
  device_type: Platform.OS,
  jobReference: "",
  parent_branch: "",
  last_screen: "STCReviewOrders",
  userId: "",
  accountId: "",
  loginStatus: "login",
  u1: "shashika.abeysuriya",
  u2: "fbu.com",
  u3: "08ad3389d5978ef528dfdf2bf08bbc8d",
  order_id: "",
  suspended_id: "",
  packing_id: "",
  stcFlowCount: 1,
  addedUsing: "Skip The Counter",
  storeName: "",
  items: [
    {
      item_id: "2800027",
      item_name: "GIB STANDARD 2400X1200 10MM WALLBOARD",
      price: 11,
      item_brand: "",
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
      quantity: 1,
    },
  ],
  transaction_id: "",
  value: 11,
  currency: "",
};

export const stockQuantityObj = {
  data: {
    customer: {
      products: [
        {
          customerPriceGstExcl: 19.85,
          customerPriceGstIncl: 22.83,
          quantity: 816,
          retailGstExclusive: 25.29,
          retailGstInclusive: 29.08,
          sku: 2800027,
          statusCode: 1,
          stockMessage: "Stock Available",
        },
      ],
    },
  },
};
export const SampleAccountsData = {
  jobAccounts: {
    selectedJobAccount: {
      SearchName: "ANTS GENERAL002",
      JobName: "Ants General Contracting2",
      JobNumber: "ANTGA002",
      Address1: "Tairua",
      Address2: "Tairua",
      JobId: "362ANTGA002",
    },
  },
  connectTrade: {
    selectedTradeAccount: {
      branch: {
        branchCode: "362",
        branchID: "P362",
        branchLegalName: "Mcgill Building Supplies Ltd",
        name: "Thames",
      },
      custId: "ANTGA",
      masterOnHold: false,
      name: "Ants General Contracting",
      uid: "362ANTGA",
    },
  },
};

export const SampleAccountsData1 = {
  jobAccounts: {
    selectedJobAccount: undefined,
  },
  connectTrade: {
    selectedTradeAccount: {
      branch: {
        branchCode: "362",
        branchID: "P362",
        branchLegalName: "Mcgill Building Supplies Ltd",
        name: "Thames",
      },
      custId: "ANTGA",
      masterOnHold: false,
      name: "Ants General Contracting",
      uid: "362ANTGA",
    },
  },
};

export const teamMemberInputParams = {
  data: {
    permissionList: ["viewOrderGroup", "restrictPriceGroup", "placeOrderGroup"],
    temporaryAccess: "true",
    startDate: "19/04/2021",
    endDate: "22/04/2021",
    mobileNumber: "643432724377",
    isAdmin: "false",
    name: "Faraz Ubit",
  },
  event: "memberAdded",
  userId: "auth0|5fb1b8465088f80075cd2192",
  accountId: "362ANTGA002",
  locationStr: "-36.803304, 174.697899",
  storeName: "Thames",
};

export const teamMemberReturnedObject = {
  event: "memberAdded",
  userId: "auth0|5fb1b8465088f80075cd2192",
  accountId: "362ANTGA002",
  admin: "false",
  viewOrders: "true",
  viewPricing: "true",
  placeOrders: "true",
  tempAccess: "true",
  location: "-36.803304, 174.697899",
  storeName: "Thames",
  device_type: Platform.OS,
};

export const productDetailInputParams = {
  event: "view_item",
  digitalId: "auth0|5fb1b8465088f80075cd2192",
  selectedAccountId: "362ANTGA",
  sanitizedData: {
    BranchId: "362",
    AccountCustomerId: "ANTGA",
    JobAccountId: "ANTGA",
    SKU: "4508305",
    ProductDescription: "Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
    UOM: "EA",
    Availability: "548 in stock",
    Price: 0.77,
    Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Bremick_WSQMG125066.jpg",
    Brand: "BREMICK",
    IsTimberProduct: false,
    SelectedMultiple: "0",
    UniqueId: "4508305-0",
    uomFormat: "11",
    sellOrderMultiple: "0",
    timberProductFlag: false,
    IsExpressOrder: true,
    StockQuantity: "548",
  },
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
};

export const productDetailReturnedObject = {
  event: "view_item",
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
  device_type: "ios",
  userId: "auth0|5fb1b8465088f80075cd2192",
  accountId: "362ANTGA",
  items: [
    {
      item_name: "Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
      item_id: "4508305",
      price: 0.77,
      item_brand: "BREMICK",
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
    },
  ],
};

export const productSelectInputParams = {
  index: 1,
  event: "select_item",
  digitalId: "auth0|5fb1b8465088f80075cd2192",
  selectedAccountId: "362ANTGA",
  sanitizedData: {
    BranchId: "362",
    AccountCustomerId: "ANTGA",
    JobAccountId: "ANTGA",
    SKU: "4508305",
    ProductDescription: "Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
    UOM: "EA",
    Availability: "548 in stock",
    Price: 0.77,
    Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Bremick_WSQMG125066.jpg",
    Brand: "Bremick",
    IsTimberProduct: false,
    SelectedMultiple: "0",
    UniqueId: "4508305-0",
    uomFormat: "11",
    sellOrderMultiple: "0",
    timberProductFlag: false,
    IsExpressOrder: true,
    StockQuantity: "548",
  },
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
};

export const productSelectReturnedObject = {
  event: "select_item",
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
  device_type: "ios",
  userId: "auth0|5fb1b8465088f80075cd2192",
  accountId: "362ANTGA",
  items: [
    {
      item_name: "Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
      item_id: "4508305",
      price: 0.77,
      item_brand: "Bremick",
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
      item_list_name: "Product List View",
      index: 1,
    },
  ],
};

export const productListViewInputParams = {
  event: "view_item_list",
  digitalId: "auth0|5fb1b8465088f80075cd2192",
  selectedAccountId: "362ANTGA",
  sanitizedData: [
    {
      BranchId: "362",
      AccountCustomerId: "ANTGA",
      JobAccountId: "ANTGA",
      SKU: "1015262",
      ProductDescription: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
      UOM: "LM",
      Availability: "4149 in stock",
      Price: 4.88,
      Image: "https://pimstorageaueuat.blob.core.windows.net/placemakers/media-assets/No-image-found_v2.jpg",
      Brand: "",
      IsTimberProduct: true,
      SelectedMultiple: "6",
      UniqueId: "1015262-6",
      uomFormat: "7.2",
      sellOrderMultiple: "6",
      timberProductFlag: true,
      IsExpressOrder: false,
      StockQuantity: "4149",
    },
    {
      BranchId: "362",
      AccountCustomerId: "ANTGA",
      JobAccountId: "ANTGA",
      SKU: "4508305",
      ProductDescription: "Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
      UOM: "EA",
      Availability: "548 in stock",
      Price: 0.77,
      Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Bremick_WSQMG125066.jpg",
      Brand: "Bremick",
      IsTimberProduct: false,
      SelectedMultiple: "0",
      UniqueId: "4508305-0",
      uomFormat: "11",
      sellOrderMultiple: "0",
      timberProductFlag: false,
      IsExpressOrder: true,
      StockQuantity: "548",
    },
  ],
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
};

export const productListViewReturnedObject = {
  event: "view_item_list",
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
  device_type: "ios",
  userId: "auth0|5fb1b8465088f80075cd2192",
  accountId: "362ANTGA",
  items: [
    {
      item_name: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
      item_id: "1015262",
      price: 4.88,
      item_brand: "",
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
      item_list_name: "Product List View",
      index: 0,
    },
    {
      item_name: "Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
      item_id: "4508305",
      price: 0.77,
      item_brand: "Bremick",
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
      item_list_name: "Product List View",
      index: 1,
    },
  ],
};

export const productListSearchInputParams = {
  event: "view_item_list",
  digitalId: "auth0|5fb1b8465088f80075cd2192",
  selectedAccountId: "362ANTGA",
  sanitizedData: [
    {
      BranchId: "362",
      AccountCustomerId: "ANTGA",
      JobAccountId: "ANTGA",
      SKU: "1015262",
      ProductDescription: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
      UOM: "LM",
      Availability: "4149 in stock",
      Price: 4.88,
      Image: "https://pimstorageaueuat.blob.core.windows.net/placemakers/media-assets/No-image-found_v2.jpg",
      Brand: "",
      IsTimberProduct: true,
      SelectedMultiple: "6",
      UniqueId: "1015262-6",
      uomFormat: "7.2",
      sellOrderMultiple: "6",
      timberProductFlag: true,
      IsExpressOrder: false,
      StockQuantity: "4149",
    },
    {
      BranchId: "362",
      AccountCustomerId: "ANTGA",
      JobAccountId: "ANTGA",
      SKU: "4508305",
      ProductDescription: "Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
      UOM: "EA",
      Availability: "548 in stock",
      Price: 0.77,
      Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/Bremick_WSQMG125066.jpg",
      Brand: "Bremick",
      IsTimberProduct: false,
      SelectedMultiple: "0",
      UniqueId: "4508305-0",
      uomFormat: "11",
      sellOrderMultiple: "0",
      timberProductFlag: false,
      IsExpressOrder: true,
      StockQuantity: "548",
    },
  ],
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
  searchTerm: "Bremick",
};

export const productListSearchReturnedObject = {
  event: "view_item_list",
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
  device_type: "ios",
  userId: "auth0|5fb1b8465088f80075cd2192",
  accountId: "362ANTGA",
  searchTerm: "Bremick",
  searchResults: 2,
  items: [
    {
      item_name: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
      item_id: "1015262",
      price: 4.88,
      item_brand: "",
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
      item_list_name: "Search Results",
      index: 0,
    },
    {
      item_name: "Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
      item_id: "4508305",
      price: 0.77,
      item_brand: "Bremick",
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
      item_list_name: "Search Results",
      index: 1,
    },
  ],
};

export const myListInputParams = {
  event: "view_item_list",
  digitalId: "auth0|5fb1b8465088f80075cd2192",
  selectedAccountId: "362ANTGA",
  sanitizedData: [
    {
      BranchId: "362",
      AccountCustomerId: "ANTGA",
      JobAccountId: "ANTGA",
      SKU: "1015262",
      ProductDescription: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
      UOM: "LM",
      Availability: "4149 in stock",
      Price: 4.88,
      Image: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1169332_100X50(90X45)RAD-SG8-H1.2-PG-KD.jpg",
      Brand: "",
      IsTimberProduct: true,
      SelectedMultiple: "6",
      UniqueId: "1015262-6",
      uomFormat: "7.2",
      sellOrderMultiple: "6",
      timberProductFlag: true,
      IsExpressOrder: false,
      StockQuantity: "4149",
    },
  ],
  listName: "My List",
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
};

export const myListReturnedObject = {
  event: "view_item_list",
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
  device_type: "ios",
  userId: "auth0|5fb1b8465088f80075cd2192",
  accountId: "362ANTGA",
  items: [
    {
      item_name: "Radiata SG8 Kiln Dried H1.2 Treated 100 x 50mm (90 x 45mm) 6.0m",
      item_id: "1015262",
      price: 4.88,
      item_brand: "",
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
      item_stock: "4149 in stock",
      item_list_name: "My List",
      index: 0,
    },
  ],
};

export const cartItemInputParams = {
  event: "remove_from_cart",
  digitalId: "auth0|5fb1b8465088f80075cd2192",
  selectedAccountId: "362ANTGA",
  data: {
    item: {
      availableForPickup: true,
      basePrice: {
        currencyIso: "NZD",
        formattedValue: "$0.77",
        priceType: "BUY",
        value: 0.77,
      },
      configurationInfos: [],
      decimalQty: 1,
      deliveryOrder: true,
      entryNumber: 0,
      product: {
        availableForPickup: true,
        baseOptions: [],
        categories: [],
        code: "4508305",
        configurable: false,
        description:
          "The Bremick M12 Square Washer is designed for use in applications with any nuts, bolts and screw products. It measures 50 mm x 3 mm. This washer helps to prevent a nut or bolt head from pulling through the material. Washer with a hole in the centre can be used as a spacer.It features galvanised steel construction for long lasting durability and superior corrosion resistance. This washer is suitable for use in exterior applications including coastal zones. It helps to minimise the surface damage of the work material.",
        expressOrder: true,
        hasNoQuantity: 0,
        images: [
          {
            altText: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
            format: "zoom",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1033589_Bremick_WSQMG125066.jpg",
          },
          {
            altText: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
            format: "product",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1033589_Bremick_WSQMG125066.jpg",
          },
          {
            altText: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
            format: "thumbnail",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1033589_Bremick_WSQMG125066.jpg",
          },
          {
            altText: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
            format: "cartIcon",
            imageType: "PRIMARY",
            url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1033589_Bremick_WSQMG125066.jpg",
          },
        ],
        manufacturer: "BREMICK",
        name: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
        price: {
          currencyIso: "NZD",
          formattedValue: "$0.77",
          priceType: "BUY",
          value: 0.77,
        },
        purchasable: true,
        sellOrderMultiple: 0,
        stock: {
          pmStockQuantity: "548",
          statusCode: "1",
          stockLevelStatus: "inStock",
        },
        timberProductFlag: false,
        unitCode: "EA",
        uomFormat: "11",
        url: "/c/Bremick-Flat-Square-Washer-M12-x-50-x-3mm-Galvanised-WSQMG125036/p/4508305",
      },
      quantity: 1,
      totalPrice: {
        currencyIso: "NZD",
        formattedValue: "$0.77",
        priceType: "BUY",
        value: 0.77,
      },
      unit: "EA",
      updateable: true,
    },
    quantity: 1,
    update: " updateCart() ",
    setQuantity: " bound dispatchAction() ",
    digitalId: "auth0|5fb1b8465088f80075cd2192",
    selectedAccountId: "362ANTGA",
    selectedBranch: {
      address: {
        country: {
          isocode: "NZ",
          name: "New Zealand",
        },
        defaultAddress: false,
        email: "thamessitbranch@fbu.com",
        formattedAddress: "P O BOX 510, 73 KOPU RD, Waikato and BOP, 3500",
        id: "8796617342999",
        line1: "P O BOX 510",
        line2: "73 KOPU RD",
        phone: "(07)868-0130",
        postalCode: "3500",
        region: {
          countryIso: "NZ",
          isocode: "NZ-BOP",
          isocodeShort: "BOP",
          name: "Bay of Plenty",
        },
        shippingAddress: false,
        town: "Waikato and BOP",
        visibleInAddressBook: true,
      },
      branchCode: "362",
      branchID: "P362",
      branchLegalName: "MCGILL BUILDING SUPPLIES LTD",
      branchRegionalCode: "NZ-BOP",
      features: {},
      geoPoint: {
        latitude: -37.6190862,
        longitude: 175.023346,
      },
      isActive: true,
      isBranch: true,
      name: "Thames",
      openingHours: {
        code: "362-Working Hours",
        specialDayOpeningList: [],
        weekDayOpeningList: [
          {
            closingTime: {
              formattedHour: "17:00",
              hour: 5,
              minute: 0,
            },
            openingTime: {
              formattedHour: "07:00",
              hour: 7,
              minute: 0,
            },
            closed: false,
            weekDay: "Mon",
          },
          {
            closingTime: {
              formattedHour: "17:00",
              hour: 5,
              minute: 0,
            },
            openingTime: {
              formattedHour: "07:00",
              hour: 7,
              minute: 0,
            },
            closed: false,
            weekDay: "Tue",
          },
          {
            closingTime: {
              formattedHour: "17:00",
              hour: 5,
              minute: 0,
            },
            openingTime: {
              formattedHour: "07:00",
              hour: 7,
              minute: 0,
            },
            closed: false,
            weekDay: "Wed",
          },
          {
            closingTime: {
              formattedHour: "17:00",
              hour: 5,
              minute: 0,
            },
            openingTime: {
              formattedHour: "07:00",
              hour: 7,
              minute: 0,
            },
            closed: false,
            weekDay: "Thu",
          },
          {
            closingTime: {
              formattedHour: "17:00",
              hour: 5,
              minute: 0,
            },
            openingTime: {
              formattedHour: "07:00",
              hour: 7,
              minute: 0,
            },
            closed: false,
            weekDay: "Fri",
          },
          {
            closingTime: {
              formattedHour: "12:30",
              hour: 0,
              minute: 30,
            },
            openingTime: {
              formattedHour: "08:00",
              hour: 8,
              minute: 0,
            },
            closed: false,
            weekDay: "Sat",
          },
          {
            closingTime: {
              hour: 0,
              minute: 0,
            },
            openingTime: {
              hour: 0,
              minute: 0,
            },
            closed: false,
            weekDay: "Sun",
          },
        ],
      },
      parentBranchID: "P362",
      storeImages: [],
    },
  },
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
};

export const cartItemInputParams1 = {
  event: "remove_from_cart",
  digitalId: "auth0|5fb1b8465088f80075cd2192",
  selectedAccountId: "362ANTGA",
  data: {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$0.77",
      priceType: "BUY",
      value: 0.77,
    },
    configurationInfos: [],
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 0,
    product: {
      availableForPickup: true,
      baseOptions: [],
      categories: [],
      code: "4508305",
      configurable: false,
      description:
        "The Bremick M12 Square Washer is designed for use in applications with any nuts, bolts and screw products. It measures 50 mm x 3 mm. This washer helps to prevent a nut or bolt head from pulling through the material. Washer with a hole in the centre can be used as a spacer.It features galvanised steel construction for long lasting durability and superior corrosion resistance. This washer is suitable for use in exterior applications including coastal zones. It helps to minimise the surface damage of the work material.",
      expressOrder: true,
      hasNoQuantity: 0,
      images: [
        {
          altText: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
          format: "zoom",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1033589_Bremick_WSQMG125066.jpg",
        },
        {
          altText: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
          format: "product",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1033589_Bremick_WSQMG125066.jpg",
        },
        {
          altText: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
          format: "thumbnail",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1033589_Bremick_WSQMG125066.jpg",
        },
        {
          altText: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
          format: "cartIcon",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1033589_Bremick_WSQMG125066.jpg",
        },
      ],
      manufacturer: "BREMICK",
      name: "Bremick Flat Square Washer M12 x 50 x 3mm Galvanised WSQMG125036",
      price: {
        currencyIso: "NZD",
        formattedValue: "$0.77",
        priceType: "BUY",
        value: 0.77,
      },
      purchasable: true,
      sellOrderMultiple: 0,
      stock: {
        pmStockQuantity: "548",
        statusCode: "1",
        stockLevelStatus: "inStock",
      },
      timberProductFlag: false,
      unitCode: "EA",
      uomFormat: "11",
      url: "/c/Bremick-Flat-Square-Washer-M12-x-50-x-3mm-Galvanised-WSQMG125036/p/4508305",
    },
    quantity: 1,
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.77",
      priceType: "BUY",
      value: 0.77,
    },
    unit: "EA",
    updateable: true,
  },
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
};

export const cartItemReturnedObject = {
  event: "remove_from_cart",
  location: "Waikato and BOP, Bay of Plenty",
  storeName: "Thames",
  device_type: "ios",
  userId: "auth0|5fb1b8465088f80075cd2192",
  accountId: "362ANTGA",
  items: [
    {
      item_name: undefined,
      item_id: undefined,
      price: 0,
      item_brand: undefined,
      item_category: "",
      item_category_2: "",
      item_category_3: "",
      item_category_4: "",
      item_variant: "",
      quantity: NaN,
    },
  ],
};
