import { combineEpics } from "redux-observable";
import {
  epicAddressDistanceDriveTime,
  epicAddressGeoCode,
  epicAddressValidation,
  epicAddUpdateDeliveryAddress,
  epicJobAccountAndBranches,
  epicJobAccounts,
  epicPlaceOrder,
  epicRequestPreviouslyUsedAddresses,
} from "~root/Epics/AddressConfirmation";
import { epicFetchRemoteConfigs } from "~root/Epics/AppEpics";
import { epicBarcodeSearchSolr } from "~root/Epics/BarcodeEpics";
import {
  epicGetBranchDetails,
  epicGetBranchList,
  epicGetNearByBranchList,
  epicGetOrderFulfilmentBranchDetails,
  epicGetStockAvailabilty,
} from "~root/Epics/BranchEpics";
import {
  epicAddProductToCart,
  epicApplyVoucher,
  epicCartFailure,
  epicCartItemQuantity,
  epicCartItemUpdateMap,
  epicClearCart,
  epicDeleteAppliedVoucher,
  epicDeleteCartItem,
  epicDeleteCartItemMap,
  epicDeleteContactDetails,
  epicDeleteItem,
  epicFulfilmentEligibility,
  epicGetDeliveryRequirements,
  epicSaveCartContactDetails,
  epicSaveCartInfo,
  epicSaveDeliveryInfoToUserSessionCart,
  epicSTCCartStockPrice,
  epicSwapCartProduct,
  epicUpdateCart,
  epicUserCartRequest,
  getCartDetailsRequest,
} from "~root/Epics/CartEpics";
import { epicContactStreamline } from "~root/Epics/ContactStreamlineEpics";
import { epicGetCountryList } from "~root/Epics/CountryListEpic";
import { epicDeleteInvite, epicSendInvite, epicUpdateInvite, epicUpdatePermission } from "~root/Epics/EditPermissionEpics";
import { epicEmailSuccessListener, epicSendEmail } from "~root/Epics/EmailEpics";
import { epicEstimatesList, epicEstimatesListById, epicEstimatesListDetails } from "~root/Epics/EstimatesEpic";
import {
  epicCheckLoginDb,
  epicGetUserInfo,
  epicLogout,
  epicRefreshToken,
  epicRequestError503,
  epicTokenSuccess,
  epicUnAuthorizedCall,
  epicUserSuccess,
} from "~root/Epics/LoginEpics";
import { epicGetContacts, epicGetInviteDetails, epicSearchContacts, epicSetTeamData } from "~root/Epics/ManageTeamEpics";
import { epicGetMarketingTileInfo } from "~root/Epics/MarketingEpics";
import { epicCreateSectionsSOBQuotes, epicDeleteSectionsSOBQuotes, epicGetSOBQuotes } from "~root/Epics/MaterialSectionsSOBQuotesEpic";
import { epicGetInboxMessages, epicNotificationReceived, epicNotificationsViewed } from "~root/Epics/NotificationEpics";
import { epicExistingOrderList, epicOnOrderSuccess, epicOrderList } from "~root/Epics/OrderAndDeliveries";
import { epicOrderDetails } from "~root/Epics/OrderDetails";
import {
  epicCheckOrderToProcessInDb,
  epicConfirmOrder,
  epicOrderHistoryRequest,
  epicRequestOrderReview,
  epicResumeOrderRequest,
  epicSTCRequestOrderReview,
  epicUpdateOrderHistoryItem,
} from "~root/Epics/OrderHistoryEpics";
import { epicProductClear, epicProductDetails, epicRelatedAndSubstituteProducts } from "~root/Epics/ProductEpics";
import {
  epicAddOwnProduct,
  epicChangeQuoteStatus,
  epicCreateLabourCost,
  epicDefaultDisplayOptionsForQuotes,
  epicDeleteLabourCost,
  epicDeleteQuote,
  epicDeleteQuoteMedia,
  epicDeleteQuoteProduct,
  epicGetCompanyDetails,
  epicGetQuoteMedia,
  epicGetQuoteProducts,
  epicMarkComplete,
  epicMaterialsReprice,
  epicNewJob,
  epicQuotesList,
  epicQuotesListDetails,
  epicRequestLabourCost,
  epicSendEmailQuote,
  epicSwapProduct,
  epicUpdateDisplayOptionsForQuotes,
  epicUpdateLabourCost,
  epicUpdateQuoteCompanyDetails,
  epicUpdateQuoteDetails,
  epicUpdateQuoteJobStatus,
  epicUpdateQuoteMarkupPercent,
  epicUpdateQuoteMedia,
  epicUpdateQuoteProductQuantity,
  epicuploadImageFileToQuote,
  epicViewQuote,
} from "~root/Epics/QuotesEpic";
import {
  epicAddItemForNewList,
  epicAddItemToList,
  epicAddList,
  epicFrequentProducts,
  epicGetAllList,
  epicListDetail,
  epicRemoveItemFromList,
  epicRemoveList,
  epicRenameList,
  epicSearchSolr,
  epicSearchSuggestions,
  epicTopCategoryProducts,
} from "~root/Epics/SearchEpics";
import {
  epicGetUpdateUserStatus,
  epicGetUpdateUserTradeAccountStatus,
  epicGetUserTradeAccountList,
  epicLinkTradeAccountAtSignup,
} from "~root/Epics/SignUpEpic";
import { epicRequestExpiryToken, epicSTCAuthTokenRequest, epicSTCOnTradeAccountSelection } from "~root/Epics/StcEpics";
import { epicGetSubCategories } from "~root/Epics/SubCategoriesEpics";
import {
  epicGetTradeAccountFilteredList,
  epicGetTradeAccountList,
  epicNewTradeAccountAdded,
  epicOnTradeAccountSelection,
  epicSelectJobAccount,
  epicTradeAccount,
  epicValidatePermissions,
} from "~root/Epics/TradeAccountEpics";
import { epicGetPaymentStatus } from "./PaymentEpics";
import { epicLogPixelEvent } from "./PixelEpics";

export default combineEpics(
  epicFrequentProducts,
  epicOrderList,
  epicOnOrderSuccess,
  epicLogout,
  epicTokenSuccess,
  epicClearCart,
  epicUpdateCart,
  epicOrderDetails,
  epicAddressValidation,
  epicJobAccounts,
  epicAddressGeoCode,
  epicSendEmail,
  epicEmailSuccessListener,
  epicGetContacts,
  epicSetTeamData,
  epicCheckLoginDb,
  epicUpdatePermission,
  epicUpdateInvite,
  epicSendInvite,
  epicDeleteInvite,
  epicGetBranchList,
  epicGetCountryList,
  epicGetInviteDetails,
  epicSearchContacts,
  epicTradeAccount,
  epicGetUpdateUserStatus,
  epicUserSuccess,
  epicGetUpdateUserTradeAccountStatus,
  epicGetTradeAccountFilteredList,
  epicSearchSolr,
  epicAddItemToList,
  epicRemoveItemFromList,
  epicRemoveList,
  epicAddList,
  epicListDetail,
  epicAddItemForNewList,
  epicGetAllList,
  epicProductClear,
  epicRefreshToken,
  epicUnAuthorizedCall,
  epicOnTradeAccountSelection,
  epicGetTradeAccountList,
  epicValidatePermissions,
  epicRequestError503,
  epicJobAccountAndBranches,
  epicSTCAuthTokenRequest,
  epicRequestExpiryToken,
  epicOrderHistoryRequest,
  epicUpdateOrderHistoryItem,
  epicCheckOrderToProcessInDb,
  epicRequestOrderReview,
  epicSTCOnTradeAccountSelection,
  epicConfirmOrder,
  epicGetUserTradeAccountList,
  epicLinkTradeAccountAtSignup,
  epicGetUserInfo,
  epicSearchSuggestions,
  epicProductDetails,
  epicDeleteSectionsSOBQuotes,
  epicRelatedAndSubstituteProducts,
  epicRenameList,
  epicBarcodeSearchSolr,
  epicDeleteItem,
  epicSTCRequestOrderReview,
  epicSTCCartStockPrice,
  epicNotificationReceived,
  epicGetMarketingTileInfo,
  epicLogPixelEvent,
  epicGetNearByBranchList,
  epicGetBranchDetails,
  epicGetStockAvailabilty,
  epicResumeOrderRequest,
  epicGetOrderFulfilmentBranchDetails,
  epicUserCartRequest,
  epicAddProductToCart,
  getCartDetailsRequest,
  epicCartItemQuantity,
  epicDeleteCartItem,
  epicGetInboxMessages,
  epicApplyVoucher,
  epicDeleteAppliedVoucher,
  epicCartItemUpdateMap,
  epicDeleteCartItemMap,
  epicNotificationsViewed,
  epicFulfilmentEligibility,
  epicAddUpdateDeliveryAddress,
  epicPlaceOrder,
  epicSaveDeliveryInfoToUserSessionCart,
  epicSaveCartContactDetails,
  epicRequestPreviouslyUsedAddresses,
  epicContactStreamline,
  epicDeleteContactDetails,
  epicExistingOrderList,
  epicGetSubCategories,
  epicTopCategoryProducts,
  epicCartFailure,
  epicSaveCartInfo,
  epicFetchRemoteConfigs,
  epicEstimatesList,
  epicEstimatesListDetails,
  epicEstimatesListById,
  epicQuotesList,
  epicQuotesListDetails,
  epicGetQuoteProducts,
  epicUpdateQuoteProductQuantity,
  epicAddOwnProduct,
  epicSwapProduct,
  epicDeleteQuoteProduct,
  epicUpdateQuoteMarkupPercent,
  epicRequestLabourCost,
  epicUpdateQuoteDetails,
  epicUpdateQuoteJobStatus,
  epicUpdateQuoteCompanyDetails,
  epicNewJob,
  epicCreateLabourCost,
  epicNewTradeAccountAdded,
  epicDeleteLabourCost,
  epicGetCompanyDetails,
  epicUpdateLabourCost,
  epicSelectJobAccount,
  epicViewQuote,
  epicMarkComplete,
  epicMaterialsReprice,
  epicSendEmailQuote,
  epicChangeQuoteStatus,
  epicCreateSectionsSOBQuotes,
  epicGetSOBQuotes,
  epicuploadImageFileToQuote,
  epicGetQuoteMedia,
  epicDefaultDisplayOptionsForQuotes,
  epicUpdateDisplayOptionsForQuotes,
  epicDeleteQuoteMedia,
  epicUpdateQuoteMedia,
  epicDeleteQuote,
  epicAddressDistanceDriveTime,
  epicGetDeliveryRequirements,
  epicSwapCartProduct,
  epicGetPaymentStatus,
);
