require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '13.0'


  project 'FletcherBuilderTradeApp',
  'Debug' => :debug,
  'Release' => :release,
  'DEV.Debug' => :debug,
  'DEV.Release' => :release,
  'UAT.Debug' => :debug,
  'UAT.Release' => :release,
  'SIT.Debug' => :debug,
  'SIT.Release' => :release,
  'BAU.Debug' => :debug,
  'BAU.Release' => :release

target 'PlaceMakers Trade App' do
  #target 'FletcherBuilderTradeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FletcherBuilderTradeApp
  pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer/ios/'
  pod 'GoogleTagManager'
  pod 'MQTTClient'
  pod 'NewRelicAgent'
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'Evergage', '~> 1.3'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
  )

  # Permissions
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle" # <--- this
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
end
