export const estimatesResponseData = {
  branchId: 362,
  tradeaccount: "ADITA",
  jobaccount: "ADITA004",
  estimateNumber: "35405",
  sectionId: "4900",
  sectionDescription: "Concrete Systems",
  estimateList: [
    {
      accountName: "Block A 810 Grea",
      accountId: "ADITA004",
      estimateNumber: "35405",
      estimateDate: "2021-05-04T00:00:00",
      estimateExpire: "2021-10-11T00:00:00",
      estimateTotal: "9997.64",
      custPo: "",
      projectName: "Block A 810 Grea",
      projectNumber: "21-00180581",
      section: [
        {
          sectionId: 1000,
          sectionDescription: "Profiles",
          lineCount: "2",
          lines: [],
        },
        {
          sectionId: 3000,
          sectionDescription: "Reinforcing Steel",
          lineCount: "2",
          lines: [],
        },
        {
          sectionId: 4000,
          sectionDescription: "Foundation Hardware",
          lineCount: "4",
          lines: [],
        },
        {
          sectionId: 4900,
          sectionDescription: "Concrete Systems",
          lineCount: "11",
          lines: [
            {
              lineNumber: 9,
              sku: "1152073",
              textskuId: 260756883,
              description: "300 X 25 MM RAD BOX UT RS",
              custProdDescription: "300x25mm Rad Box Untreated RS [Ribraft Slab Edge]",
              qtyEstimated: 27.0,
              qtyLengthBreakdowns: [],
              unitOfMeasure: "LM",
              unitDescription: "LINEAL METRE",
              unitPrice: 4.47,
              extLineTotalExcl: 120.69,
              gstAmount: 18.1,
              soh: 400.4,
              soMultiple: 0.0,
              estimateSoh: 100,
            },
            {
              lineNumber: 10,
              sku: "1015021",
              textskuId: 1162798643,
              description: "75 X 50 (70X45) RAD SG8 H1.2 PG KD",
              custProdDescription: "75 X 50 SG8 H1.2 PLANER GAUGED KILN DRIED RADIATA [Pegs To Boxing]",
              qtyEstimated: 27.0,
              qtyLengthBreakdowns: [],
              unitOfMeasure: "LM",
              unitDescription: "LINEAL METRE",
              unitPrice: 3.58,
              extLineTotalExcl: 96.66,
              gstAmount: 14.5,
              soh: -242.6,
              soMultiple: 0.0,
              estimateSoh: 100,
            },
          ],
        },
        {
          sectionId: 18000,
          sectionDescription: "Miscellaneous Framing",
          lineCount: "1",
          lines: [],
        },
        {
          sectionId: 19000,
          sectionDescription: "Wall and Roof Hardware",
          lineCount: "9",
          lines: [],
        },
        {
          sectionId: 20000,
          sectionDescription: "Roof Framing",
          lineCount: "5",
          lines: [],
        },
        {
          sectionId: 21000,
          sectionDescription: "Soffits",
          lineCount: "4",
          lines: [],
        },
        {
          sectionId: 23000,
          sectionDescription: "Prenail Frames",
          lineCount: "1",
          lines: [],
        },
        {
          sectionId: 25000,
          sectionDescription: "Trusses",
          lineCount: "1",
          lines: [],
        },
        {
          sectionId: 26000,
          sectionDescription: "Ceilings",
          lineCount: "3",
          lines: [],
        },
        {
          sectionId: 27000,
          sectionDescription: "Exterior Cladding and Trim",
          lineCount: "14",
          lines: [],
        },
        {
          sectionId: 29000,
          sectionDescription: "Interior Linings and Trim",
          lineCount: "9",
          lines: [],
        },
        {
          sectionId: 29040,
          sectionDescription: "Slats & Shelving",
          lineCount: "1",
          lines: [],
        },
        {
          sectionId: 31500,
          sectionDescription: "Door Hardware",
          lineCount: "1",
          lines: [],
        },
        {
          sectionId: 33000,
          sectionDescription: "Sundry and Consumables",
          lineCount: "3",
          lines: [],
        },
        {
          sectionId: 24900,
          sectionDescription: "Structural Steel",
          lineCount: "1",
          lines: [],
        },
      ],
    },
  ],
};

export const expectedLinesData = [
  {
    Brand: "",
    Image: "",
    Price: "NaN",
    AvailableForPickup: false,
    SKU: "",
    ProductDescription: "",
    estimateDescription: "",
    estimateProductDesc: "",
    hasAlternateProducts: false,
    hasRelatedProducts: false,
    IsTimberProduct: false,
    uomFormat: 0,
    sellOrderMultiple: 0,
    SelectedMultiple: 0,
    Stock: "100 in stock",
    UOM: "",
    StockQuantity: 100,
    EstimatedQuantity: "",
    IsExpressOrder: "",
    EstimateLineNumber: "",
    IsSpecial: false,
    EstimateProductFlag: false,
    EstimateProductUnit: "",
    UniqueId: "-0",
    stock: { IsEstimate: true, estimateSoh: 100 },
    PmExclusive: false,
    alternateProductCount: 0,
    relatedProductCount: 0,
  },
  {
    Brand: "",
    Image: "",
    Price: "NaN",
    AvailableForPickup: false,
    SKU: "",
    ProductDescription: "",
    estimateDescription: "",
    estimateProductDesc: "",
    hasAlternateProducts: false,
    hasRelatedProducts: false,
    IsTimberProduct: false,
    uomFormat: 0,
    sellOrderMultiple: 0,
    SelectedMultiple: 0,
    Stock: "100 in stock",
    UOM: "",
    StockQuantity: 100,
    EstimatedQuantity: "",
    IsExpressOrder: "",
    EstimateLineNumber: "",
    IsSpecial: false,
    EstimateProductFlag: false,
    EstimateProductUnit: "",
    UniqueId: "-0",
    stock: { IsEstimate: true, estimateSoh: 100 },
    PmExclusive: false,
    alternateProductCount: 0,
    relatedProductCount: 0,
  },
];
