export const AppState = {
  address: { addressSuggestions: [], fetchingAddress: false, fetching: false },
  nav: {
    key: "StackRouterRoot",
    isTransitioning: false,
    index: 0,
    routes: [
      {
        routes: [
          {
            key: "OrderDeliveries",
            isTransitioning: false,
            index: 0,
            routes: [{ routeName: "Main", key: "id-1615204630947-26" }],
            routeName: "OrderDeliveries",
          },
          {
            key: "MyLists",
            isTransitioning: false,
            index: 0,
            routes: [{ routeName: "MyLists", key: "MyLists" }],
            routeName: "MyLists",
          },
          {
            key: "Express",
            isTransitioning: false,
            index: 0,
            routes: [{ routeName: "LandingPage", key: "id-1615204630947-27" }],
            routeName: "Express",
          },
          {
            key: "ManageTeam",
            isTransitioning: false,
            index: 0,
            routes: [{ routeName: "Main", key: "id-1615204630947-28" }],
            routeName: "ManageTeam",
          },
          {
            key: "CartView",
            isTransitioning: false,
            index: 0,
            routes: [{ routeName: "Main", key: "id-1615204630947-29" }],
            routeName: "CartView",
          },
        ],
        index: 0,
        routeName: "Dashboard",
        key: "id-1615204630947-38",
      },
    ],
  },
  login: {
    userData: {
      type: "userWsDTO",
      name: "prasad",
      uid: "prasad.manakattil@fbu.com",
      cimSubscriberKey: "003O000001PZESJIA5",
      companies: [
        {
          addresses: [{ id: "8800495042583" }],
          name: "A ESTATE SOLUTIONS LIMITED",
          tradeAccounts: [
            {
              branch: {
                branchCode: "362",
                branchID: "P362",
                branchLegalName: "Mcgill Building Supplies Ltd",
                name: "Thames",
              },
              custId: "ANTGA",
              masterOnHold: false,
              name: "Ants General Contracting",
              uid: "362ANTGA",
            },
          ],
          uid: "CIM-04160",
        },
        {
          addresses: [{ id: "8800275496983" }],
          name: "Andrews Landscaping Limited",
          tradeAccounts: [
            {
              branch: {
                branchCode: "362",
                branchID: "P362",
                branchLegalName: "Mcgill Building Supplies Ltd",
                name: "Thames",
              },
              custId: "ADITA",
              masterOnHold: false,
              name: "Andrews Landscaping Limited",
              uid: "362ADITA",
            },
          ],
          uid: "CIM-158540",
        },
        {
          addresses: [{ id: "8805956222999" }],
          name: "Arjun Construction Ltd",
          tradeAccounts: [
            {
              branch: {
                branchCode: "362",
                branchID: "P362",
                branchLegalName: "Mcgill Building Supplies Ltd",
                name: "Thames",
              },
              custId: "A1JUN",
              masterOnHold: false,
              name: "Arjun Construction Ltd",
              uid: "362A1JUN",
            },
            {
              branch: {
                branchCode: "362",
                branchID: "P362",
                branchLegalName: "Mcgill Building Supplies Ltd",
                name: "Thames",
              },
              custId: "TWI7h",
              masterOnHold: false,
              name: "Dragos Test",
              uid: "362TWI7h",
            },
          ],
          uid: "CIM-158621",
        },
        {
          addresses: [{ id: "8800375144471" }],
          name: "Aa Drainage Limited",
          uid: "CIM-06992",
        },
        {
          addresses: [{ id: "8799063736343" }],
          name: "4 SITE BUILDERS LIMITED",
          tradeAccounts: [],
          uid: "CIM-04954",
        },
        {
          addresses: [{ id: "8804420517911" }],
          name: "Ace Plumbing And Drainage Limited",
          uid: "CIM-107955",
        },
        {
          addresses: [{ id: "8804540612631" }],
          tradeAccounts: [
            {
              branch: {
                branchCode: "362",
                branchID: "P362",
                branchLegalName: "Mcgill Building Supplies Ltd",
                name: "Thames",
              },
              custId: "ADARA",
              masterOnHold: false,
              name: "Ronald Adams",
              uid: "362ADARA",
            },
          ],
          uid: "CIM-158567",
        },
        {
          addresses: [{ id: "8799082020887" }],
          name: "ANDREWS LANDSCAPING LIMITED",
          tradeAccounts: [
            {
              branch: {
                branchCode: "362",
                branchID: "P362",
                branchLegalName: "Mcgill Building Supplies Ltd",
                name: "Thames",
              },
              custId: "ANDLA",
              masterOnHold: false,
              name: "Andrews Landscaping Limited",
              uid: "362ANDLA",
            },
          ],
          uid: "CIM-04628",
        },
        {
          addresses: [{ id: "8800323436567" }],
          name: "A G BLATCH LIMITED",
          tradeAccounts: [
            {
              branch: {
                branchCode: "146",
                branchID: "P146",
                branchLegalName: "Davis And Casey Building Supplies",
                name: "Wanaka",
              },
              custId: "BLAAE",
              masterOnHold: false,
              name: "A G Blatch Limited",
              uid: "146BLAAE",
            },
          ],
          uid: "CIM-07015",
        },
        {
          addresses: [{ id: "8805956648983" }],
          name: "Newac Ltd.",
          tradeAccounts: [
            {
              branch: {
                branchCode: "473",
                branchID: "P473",
                branchLegalName: "Placemakers Westgate",
                name: "Westgate",
              },
              custId: "NEWAC",
              masterOnHold: false,
              name: "Newac Ltd.",
              uid: "473NEWAC",
            },
          ],
          uid: "CIM-158638",
        },
      ],
      currency: {
        active: false,
        isocode: "NZD",
        name: "New Zeland Dollar",
        symbol: "$",
      },
      displayUid: "prasad.manakattil@fbu.com",
      isLicenseUpdated: true,
      mobileNumber: "64211859189",
      roles: ["b2bcustomergroup"],
    },
    fetching: false,
    checkingLogin: false,
    tempToken: {
      accessToken:
        "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFVVkdRMEpGT0RaQ05qVXhOVGxHTUVFM1JESXdRakkzUlVWRE5qTXhSa1pHUVRjeFJVTTJSZyJ9.eyJodHRwczovL2Vjb21tZXJjZS5wbGFjZW1ha2Vycy5jby5uei9lbWFpbCI6InByYXNhZC5tYW5ha2F0dGlsQGZidS5jb20iLCJodHRwczovL2Vjb21tZXJjZS5wbGFjZW1ha2Vycy5jby5uei9mcm9tU2lnbnVwIjpmYWxzZSwiaHR0cHM6Ly9lY29tbWVyY2UucGxhY2VtYWtlcnMuY28ubnovcGhvbmVOdW1iZXIiOiIrNjQyMTE4NTkxODkiLCJodHRwczovL2Vjb21tZXJjZS5wbGFjZW1ha2Vycy5jby5uei9zdXJuYW1lIjoibWFuYWthdHRpbCIsImh0dHBzOi8vZWNvbW1lcmNlLnBsYWNlbWFrZXJzLmNvLm56L2ZpcnN0TmFtZSI6InByYXNhZCIsImh0dHBzOi8vZWNvbW1lcmNlLnBsYWNlbWFrZXJzLmNvLm56L3RyYWRlQWNjb3VudHMiOnsidHJhZGVBY2NvdW50cyI6W3siYnJhbmNoQ29kZSI6IjM2MiIsImN1c3RJZCI6IkFOVEdBIiwidWlkIjoiMzYyQU5UR0EifSx7ImJyYW5jaENvZGUiOiIzNjIiLCJjdXN0SWQiOiJBRElUQSIsInVpZCI6IjM2MkFESVRBIn0seyJicmFuY2hDb2RlIjoiMzYyIiwiY3VzdElkIjoiQTFKVU4iLCJ1aWQiOiIzNjJBMUpVTiJ9LHsiYnJhbmNoQ29kZSI6IjM2MiIsImN1c3RJZCI6IlRXSTdoIiwidWlkIjoiMzYyVFdJN2gifSx7ImJyYW5jaENvZGUiOiI0NzMiLCJjdXN0SWQiOiJBQURSQSIsInVpZCI6IjQ3M0FBRFJBIn0seyJicmFuY2hDb2RlIjoiMzYyIiwiY3VzdElkIjoiNFNJQUEiLCJ1aWQiOiIzNjI0U0lBQSJ9LHsiYnJhbmNoQ29kZSI6IjQ5MSIsInVpZCI6IjQ5MUFDRVBMIn0seyJicmFuY2hDb2RlIjoiMzYyIiwiY3VzdElkIjoiQURBUkEiLCJ1aWQiOiIzNjJBREFSQSJ9LHsiYnJhbmNoQ29kZSI6IjM2MiIsImN1c3RJZCI6IkFORExBIiwidWlkIjoiMzYyQU5ETEEifSx7ImJyYW5jaENvZGUiOiIxNDYiLCJjdXN0SWQiOiJCTEFBRSIsInVpZCI6IjE0NkJMQUFFIn0seyJicmFuY2hDb2RlIjoiMTg3IiwiY3VzdElkIjoiQkxBQUUiLCJ1aWQiOiIxODdCTEFBRSJ9LHsiYnJhbmNoQ29kZSI6IjQ3MyIsImN1c3RJZCI6Ik5FV0FDIiwidWlkIjoiNDczTkVXQUMifV19LCJpc3MiOiJodHRwczovL3RzdC1hdXRoLnBsYWNlbWFrZXJzLmNvLm56LyIsInN1YiI6ImF1dGgwfDVlYWE5N2JjYTk5YTk4MGMwMGZlODFmOSIsImF1ZCI6WyJodHRwczovL3Rlc3QtYXBpc2VydmljZXMuZmJuemQuY28ubnovYXBpIiwiaHR0cHM6Ly9uemRpc3RyaWJ1dGlvbi1lY29tbWVyY2UtdHN0LmF1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2MTUyMDQ2MzQsImV4cCI6MTYxNTI5MTAzNCwiYXpwIjoiQmdXbGVGa09MdmI0eUZHQnBZbE9DQTV3czNFVWczVUIiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIn0.pilduuiyT-nvx9AS3C4Uj0BFQDR3oeVFQ2ykvYezBMLUCpzSHJW4wXOvWFiO-0LvryW87-zYSlm7xYsFDche39Zkr48mKXJsxG24VVX-W8YlzYmgTa8z1w9E2Qw5N4AXSuwSS08nLBloCU4rRaKspHtyZ8_tJhWs0IHlpGtP6kqlcbiTmMK9SGlli8q5q1chc5tsI63kKi81gbi4tx7L97-QRp6Ne44zE4ILxMciBH-wVOwCjsyH1NoqQ00oZuKQzRy0aLkNhVHlZGHJrEToTcLALKH7vhTfGsSAA5m5oO0ZAhE5FaL6yIEZIQQ_7wSYPBb8kMJBQSCCpmfNnA0YQw",
      idToken:
        "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFVVkdRMEpGT0RaQ05qVXhOVGxHTUVFM1JESXdRakkzUlVWRE5qTXhSa1pHUVRjeFJVTTJSZyJ9.eyJodHRwczovL2Vjb21tZXJjZS5wbGFjZW1ha2Vycy5jby5uei9lbWFpbCI6InByYXNhZC5tYW5ha2F0dGlsQGZidS5jb20iLCJodHRwczovL2Vjb21tZXJjZS5wbGFjZW1ha2Vycy5jby5uei9mcm9tU2lnbnVwIjpmYWxzZSwiaHR0cHM6Ly9lY29tbWVyY2UucGxhY2VtYWtlcnMuY28ubnovcGhvbmVOdW1iZXIiOiIrNjQyMTE4NTkxODkiLCJodHRwczovL2Vjb21tZXJjZS5wbGFjZW1ha2Vycy5jby5uei9zdXJuYW1lIjoibWFuYWthdHRpbCIsImh0dHBzOi8vZWNvbW1lcmNlLnBsYWNlbWFrZXJzLmNvLm56L2ZpcnN0TmFtZSI6InByYXNhZCIsImh0dHBzOi8vZWNvbW1lcmNlLnBsYWNlbWFrZXJzLmNvLm56L3RyYWRlQWNjb3VudHMiOnsidHJhZGVBY2NvdW50cyI6W3siYnJhbmNoQ29kZSI6IjM2MiIsImN1c3RJZCI6IkFOVEdBIiwidWlkIjoiMzYyQU5UR0EifSx7ImJyYW5jaENvZGUiOiIzNjIiLCJjdXN0SWQiOiJBRElUQSIsInVpZCI6IjM2MkFESVRBIn0seyJicmFuY2hDb2RlIjoiMzYyIiwiY3VzdElkIjoiQTFKVU4iLCJ1aWQiOiIzNjJBMUpVTiJ9LHsiYnJhbmNoQ29kZSI6IjM2MiIsImN1c3RJZCI6IlRXSTdoIiwidWlkIjoiMzYyVFdJN2gifSx7ImJyYW5jaENvZGUiOiI0NzMiLCJjdXN0SWQiOiJBQURSQSIsInVpZCI6IjQ3M0FBRFJBIn0seyJicmFuY2hDb2RlIjoiMzYyIiwiY3VzdElkIjoiNFNJQUEiLCJ1aWQiOiIzNjI0U0lBQSJ9LHsiYnJhbmNoQ29kZSI6IjQ5MSIsInVpZCI6IjQ5MUFDRVBMIn0seyJicmFuY2hDb2RlIjoiMzYyIiwiY3VzdElkIjoiQURBUkEiLCJ1aWQiOiIzNjJBREFSQSJ9LHsiYnJhbmNoQ29kZSI6IjM2MiIsImN1c3RJZCI6IkFORExBIiwidWlkIjoiMzYyQU5ETEEifSx7ImJyYW5jaENvZGUiOiIxNDYiLCJjdXN0SWQiOiJCTEFBRSIsInVpZCI6IjE0NkJMQUFFIn0seyJicmFuY2hDb2RlIjoiMTg3IiwiY3VzdElkIjoiQkxBQUUiLCJ1aWQiOiIxODdCTEFBRSJ9LHsiYnJhbmNoQ29kZSI6IjQ3MyIsImN1c3RJZCI6Ik5FV0FDIiwidWlkIjoiNDczTkVXQUMifV19LCJnaXZlbl9uYW1lIjoicHJhc2FkIiwiZmFtaWx5X25hbWUiOiJtYW5ha2F0dGlsIiwibmlja25hbWUiOiJwcmFzYWQubWFuYWthdHRpbCIsIm5hbWUiOiJwcmFzYWQubWFuYWthdHRpbEBmYnUuY29tIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzI5ZmFiMTE3Y2M5N2M2Zjg2MWM3OWI1MmJjY2QwZWM4P3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGcHIucG5nIiwidXBkYXRlZF9hdCI6IjIwMjEtMDMtMDhUMDM6MTY6MjQuNTM0WiIsImVtYWlsIjoicHJhc2FkLm1hbmFrYXR0aWxAZmJ1LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaXNzIjoiaHR0cHM6Ly90c3QtYXV0aC5wbGFjZW1ha2Vycy5jby5uei8iLCJzdWIiOiJhdXRoMHw1ZWFhOTdiY2E5OWE5ODBjMDBmZTgxZjkiLCJhdWQiOiJCZ1dsZUZrT0x2YjR5RkdCcFlsT0NBNXdzM0VVZzNVQiIsImlhdCI6MTYxNTIwNDYzNCwiZXhwIjoxNjE1MjQwNjM0fQ.JpMZhsoes58bI2p4rmXim9NKKddWrfvgwzJYkiD8bEW10wlncx5-Wu5U_fVPnG_29OZk70Xb3551iZ8m6sokQZHja06B6lfWCH4Zo-3T-zVo6-KNiJn0jrh33mz89ZrKziJL0lPWQ8piY7sRO4ePFcChwSPzPXJ2uo91dfVP0gEq_sEb8pcY9d-LEIUq0H70CTD9Pqp5i9KIm5lh6BRkV3naADfCPwrDzYy1-0MEw_4eN8ekDjQZKTb-REMLr-yelSSxzJEfLSOmJ8xfsoOcka8U2w44esRWh5x2FT7oO6gaHbEGNaTJ8IbUAC9bX3jqznQ44TWQrcvrrJ-6c_tthQ",
      scope: "openid profile email offline_access",
      expiresIn: 86400,
      tokenType: "Bearer",
    },
  },
  notification: { token: "", landedOnScreen: true, isFromNotification: false },
  connectTrade: {
    fetching: false,
    dataFiltered: [],
    selectedTradeAccount: {
      branch: {
        branchCode: "362",
        branchID: "P362",
        branchLegalName: "Mcgill Building Supplies Ltd",
        name: "Thames",
      },
      custId: "ANTGA",
      masterOnHold: false,
      name: "Ants General Contracting",
      uid: "362ANTGA",
    },
    dataTradeListUserInfo: [
      {
        title: "Thames",
        data: [
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "ANTGA",
            masterOnHold: false,
            name: "Ants General Contracting",
            uid: "362ANTGA",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "ADITA",
            masterOnHold: false,
            name: "Andrews Landscaping Limited",
            uid: "362ADITA",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "A1JUN",
            masterOnHold: false,
            name: "Arjun Construction Ltd",
            uid: "362A1JUN",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "TWI7h",
            masterOnHold: false,
            name: "Dragos Test",
            uid: "362TWI7h",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "ADARA",
            masterOnHold: false,
            name: "Ronald Adams",
            uid: "362ADARA",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "ANDLA",
            masterOnHold: false,
            name: "Andrews Landscaping Limited",
            uid: "362ANDLA",
          },
        ],
      },
      {
        title: "Wanaka",
        data: [
          {
            branch: {
              branchCode: "146",
              branchID: "P146",
              branchLegalName: "Davis And Casey Building Supplies",
              name: "Wanaka",
            },
            custId: "BLAAE",
            masterOnHold: false,
            name: "A G Blatch Limited",
            uid: "146BLAAE",
          },
        ],
      },
      {
        title: "Westgate",
        data: [
          {
            branch: {
              branchCode: "473",
              branchID: "P473",
              branchLegalName: "Placemakers Westgate",
              name: "Westgate",
            },
            custId: "NEWAC",
            masterOnHold: false,
            name: "Newac Ltd.",
            uid: "473NEWAC",
          },
        ],
      },
    ],
    searchTerm: "",
    filteredAccounts: [
      {
        title: "Thames",
        data: [
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "ANTGA",
            masterOnHold: false,
            name: "Ants General Contracting",
            uid: "362ANTGA",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "ADITA",
            masterOnHold: false,
            name: "Andrews Landscaping Limited",
            uid: "362ADITA",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "A1JUN",
            masterOnHold: false,
            name: "Arjun Construction Ltd",
            uid: "362A1JUN",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "TWI7h",
            masterOnHold: false,
            name: "Dragos Test",
            uid: "362TWI7h",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "ADARA",
            masterOnHold: false,
            name: "Ronald Adams",
            uid: "362ADARA",
          },
          {
            branch: {
              branchCode: "362",
              branchID: "P362",
              branchLegalName: "Mcgill Building Supplies Ltd",
              name: "Thames",
            },
            custId: "ANDLA",
            masterOnHold: false,
            name: "Andrews Landscaping Limited",
            uid: "362ANDLA",
          },
        ],
      },
      {
        title: "Wanaka",
        data: [
          {
            branch: {
              branchCode: "146",
              branchID: "P146",
              branchLegalName: "Davis And Casey Building Supplies",
              name: "Wanaka",
            },
            custId: "BLAAE",
            masterOnHold: false,
            name: "A G Blatch Limited",
            uid: "146BLAAE",
          },
        ],
      },
      {
        title: "Westgate",
        data: [
          {
            branch: {
              branchCode: "473",
              branchID: "P473",
              branchLegalName: "Placemakers Westgate",
              name: "Westgate",
            },
            custId: "NEWAC",
            masterOnHold: false,
            name: "Newac Ltd.",
            uid: "473NEWAC",
          },
        ],
      },
    ],
    dataTemporaryAccess: { temporaryAccess: false, endDate: "-" },
    linkableConnectAccountsCount: 0,
  },
  jobAccounts: {
    fetching: false,
    error: false,
    data: [
      {
        SearchName: "ANTS GENERAL002",
        JobName: "Ants General Contracting2",
        JobNumber: "ANTGA002",
        Address1: "Tairua",
        Address2: "Tairua",
      },
      {
        SearchName: "ANTS Job0",
        JobName: "Ants General Job0",
        JobNumber: "ANTGA000",
        Address1: "Tairua",
        Address2: "Tairua",
      },
      {
        SearchName: "ANTS GENERAL001",
        JobName: "Ants General Contracting1",
        JobNumber: "ANTGA001",
        Address1: "Tairua",
        Address2: "Tairua",
      },
    ],
  },
  quotes: {
    quoteList: [
      {
        code: "00203002",
        consumerAddress: {
          country: {
            isocode: "NZ",
          },
          defaultAddress: false,
          firstName: "Test3333 consumer address",
          formattedAddress: "Test_Tairua2222222, Test_167 Duke St, Tairua, 3544",
          id: "8800451231767",
          line1: "Test_Tairua2222222",
          line2: "Test_167 Duke St",
          phone: "1234567890",
          postalCode: "3544",
          town: "Tairua",
        },
        createdby: "deepak.rama@fbu.com",
        creationTime: "2021-10-12T03:40:34+0000",
        estimateFlag: false,
        jobAddress: {
          country: {
            isocode: "NZ",
          },
          defaultAddress: false,
          firstName: "Fence",
          formattedAddress: "test2, 167 Duke St, town, 3544",
          id: "8800451198999",
          line1: "test2",
          line2: "167 Duke St",
          postalCode: "3544",
          town: "town",
        },
        jobName: "Fence",
        materialsAddedFlag: false,
        notes: "my house",
        otherCostsAddedFlag: false,
        status: "NOTSENT",
        updatedTime: "2021-10-12T03:40:34+0000",
      },
      {
        code: "00220000",
        consumerAddress: {
          country: {
            isocode: "NZ",
          },
          defaultAddress: false,
          firstName: "Test Allens Fence",
          formattedAddress: "Test_Tairua, Test_167 Duke St, Tairua, 3544",
          id: "8800320159767",
          line1: "Test_Tairua",
          line2: "Test_167 Duke St",
          phone: "1234567890",
          postalCode: "3544",
          town: "Tairua",
        },
        createdby: "deepak.rama@fbu.com",
        creationTime: "2021-10-08T05:42:56+0000",
        estimateFlag: false,
        jobAddress: {
          country: {
            isocode: "NZ",
          },
          defaultAddress: false,
          firstName: "Allens Fence",
          formattedAddress: "Tairua, 167 Duke St, Tairua, 3544",
          id: "8800320126999",
          line1: "Tairua",
          line2: "167 Duke St",
          postalCode: "3544",
          town: "Tairua",
        },
        jobName: "Allens Fence",
        materialsAddedFlag: false,
        notes: "House end of the street",
        otherCostsAddedFlag: false,
        status: "NOTSENT",
        updatedTime: "2021-10-08T05:42:57+0000",
      },
    ],
    quotesListDetails: {
      code: "01914018",
      consumerAddress: {
        country: {
          isocode: "NZ",
          name: "New Zealand",
        },
        defaultAddress: false,
        email: "adtestuserABCDEFHHJHJHJHJHJ@gmail.com",
        firstName: "Adtest User ABCDEFGHIJKLMNOPRSTSHJH",
        formattedAddress: "810 Great South Road aaaaaaaaaaaaaaaaaaaaaaa &#@%*!^(), Penrose, Auckland 1061, CCC, Auckland, 1041",
        id: "8847080292375",
        line1: "810 Great South Road aaaaaaaaaaaaaaaaaaaaaaa &#@%*!^(), Penrose, Auckland 1061",
        line2: "CCC",
        phone: "+64 21 02765727",
        postalCode: "1041",
        shippingAddress: false,
        town: "Auckland",
        visibleInAddressBook: false,
      },
      createdby: "aditya.atitkar@fbu.com",
      creationTime: "2021-09-27T22:09:40+0000",
      estimateFlag: false,
      jobAddress: {
        country: {
          isocode: "NZ",
          name: "New Zealand",
        },
        defaultAddress: false,
        firstName: "810 Great South Road Penrose, Auckland 1061",
        formattedAddress: "810 Great South Road aaaaaaaaaaaaaaaaaaaaaaa &#@%*!^(), Penrose, Auckland 1061, CCC, Auckland, 1061",
        id: "8847080325143",
        line1: "810 Great South Road aaaaaaaaaaaaaaaaaaaaaaa &#@%*!^(), Penrose, Auckland 1061",
        line2: "CCC",
        postalCode: "1061",
        shippingAddress: false,
        town: "Auckland",
        visibleInAddressBook: false,
      },
      jobName: "810 Great South Road Penrose, Auckland 1061",
      materialsAddedFlag: true,
      notes:
        "I want to create a new quote for this customer and hope to win this I want to create a new quote for this customer and hope to win this I want to create a new quote for this customer and hope to win this I want to create a new quote for this customer and hope to win this I want to create a new quote for this customer and hope to win this I want to create a new quote for this customer and hope to win this I want to create a new quote for this customer and hope to win this I want to create a new quote",
      otherCostsAddedFlag: false,
      scopeOfWork:
        "aaaaaaaaaaaaaaaaaaaaaaaaa hdfjhasdkf akjdshfiausdf okajhdfiuadhsfkja dfkajhdsifujahds fikjahdsifjhadsjfhakdsjhfajkdhfiasdkjf oiakdsjhf  ahsoidufhaoid oiahfiuajdsh foiaudhfiuajdhf  aiduhfoiaudjhfi auhdsfiauhdfk ajhdfiuadhfhdkjad kajdhfkajhdsfo akjahdfoiaukjds lkjadhf oaiudskhfao dskljfhakdjfhaodkjfhsoifdkjhgskfdjhgoskfdljhgsklfjdhgksfdjhgsoi kfghsoikfjhgosikfjhgslkf hgpskfdhgnksjfglksjfhgkjsmdfhnlkgjs hfogk skdf aaaaaaaaaaaaaaaaaaaaaaaaa hdfjhasdkf akjdshfiausdf okajhdfiuadhsfkja dfkajhdsifujahds fikjahdsifjhadsjfhakdsjhfajkdhfiasdkjf oiakdsjhf",
      status: "NOTSENT",
      subTotal: {
        currencyIso: "NZD",
        value: 3178.95,
      },
      totalPrice: {
        currencyIso: "NZD",
        value: 3178.95,
      },
      updatedTime: "2021-10-11T15:12:46+0000",
    },
    updateQuote: {
      code: "00188001",
      createdby: "anonymous",
      creationTime: "2021-10-06T08:12:21+0000",
      estimateFlag: false,
      jobAddress: {
        country: {
          isocode: "NZ",
          name: "New Zealand",
        },
        defaultAddress: false,
        email: "shashika.abeysuriya@fbu.com",
        firstName: "s_Test Allens Fence",
        formattedAddress: "s_Test_Tairua, s_Test_167 Duke St, Tairua, 3544",
        id: "8798091935767",
        line1: "s_Test_Tairua",
        line2: "s_Test_167 Duke St",
        phone: "1234567890",
        postalCode: "3544",
        shippingAddress: false,
        town: "Tairua",
        visibleInAddressBook: false,
      },
      jobName: "s_Test Allens Fence",
      notes: "s_Updated House end of the street",
      status: "NOTSENT",
      updatedTime: "2021-10-06T08:12:22+0000",
      scopeOfWork:
        "aaaaaaaaaaaaaaaaaaaaaaaaa hdfjhasdkf akjdshfiausdf okajhdfiuadhsfkja dfkajhdsifujahds fikjahdsifjhadsjfhakdsjhfajkdhfiasdkjf oiakdsjhf  ahsoidufhaoid oiahfiuajdsh foiaudhfiuajdhf  aiduhfoiaudjhfi auhdsfiauhdfk ajhdfiuadhfhdkjad kajdhfkajhdsfo akjahdfoiaukjds lkjadhf oaiudskhfao dskljfhakdjfhaodkjfhsoifdkjhgskfdjhgoskfdljhgsklfjdhgksfdjhgsoi kfghsoikfjhgosikfjhgslkf hgpskfdhgnksjfglksjfhgkjsmdfhnlkgjs hfogk skdf aaaaaaaaaaaaaaaaaaaaaaaaa hdfjhasdkf akjdshfiausdf okajhdfiuadhsfkja dfkajhdsifujahds fikjahdsifjhadsjfhakdsjhfajkdhfiasdkjf oiakdsjhf",
    },
    quotesProducts: {
      entries: [
        {
          availableForPickup: true,
          basePrice: {
            currencyIso: "NZD",
            formattedValue: "$15.00",
            priceType: "BUY",
            value: 15.0,
          },
          configurationInfos: [],
          customProductFlag: false,
          decimalQty: 2.0,
          deliveryOrder: true,
          entryNumber: 4,
          product: {
            availableForPickup: true,
            baseOptions: [],
            categories: [],
            code: "3250867",
            configurable: false,
            expressOrder: false,
            hasNoQuantity: 40.0,
            manufacturer: "DRICON",
            manufacturerId: "HC40",
            name: "DrIcoN HANDICRETE CONCRETE 40KG 20MPA",
            purchasable: true,
            sellOrderMultiple: 0.0,
            stock: {
              stockLevel: 0,
              stockLevelStatus: "outOfStock",
            },
            timberProductFlag: false,
            unitCode: "BG",
            uomFormat: "zz,zzz,zzz,zz9-",
            url: "/c/DrIcoN-HANDICRETE-CONCRETE-40KG-20MPA/p/3250867",
          },
          quantity: 1,
          retailPrice: {
            currencyIso: "NZD",
            formattedValue: "$12.00",
            priceType: "BUY",
            value: 12.0,
          },
          totalPrice: {
            currencyIso: "NZD",
            formattedValue: "$30.00",
            priceType: "BUY",
            value: 30.0,
          },
          unit: "BG",
          updateable: true,
        },
        {
          availableForPickup: true,
          basePrice: {
            currencyIso: "NZD",
            formattedValue: "$10.00",
            priceType: "BUY",
            value: 10.0,
          },
          configurationInfos: [],
          customProductFlag: false,
          decimalQty: 1.0,
          deliveryOrder: true,
          entryNumber: 3,
          product: {
            availableForPickup: true,
            baseOptions: [],
            categories: [],
            code: "5080999",
            configurable: false,
            description:
              "The Paslode Cordless Impulse Nail and 3 Fuel Cells is suitable for use with Impulse FrameMaster-Li PowerVent nailer. This D-head nail measures 3.15 mm Dia x 90 mm. It features steel construction and bright steel finish for excellent corrosion resistance. The smooth shank provides superior holding power.",
            expressOrder: false,
            hasNoQuantity: 0.138,
            manufacturer: "PASLODE",
            manufacturerId: "B20550V",
            name: "D/H IMPULSE NAIL & 3 FUEL VALUE PACK 3.15 X 90MM BRIGHT 1000PK",
            purchasable: true,
            sellOrderMultiple: 0.0,
            stock: {
              stockLevel: 0,
              stockLevelStatus: "outOfStock",
            },
            timberProductFlag: false,
            unitCode: "KGM",
            uomFormat: "zzzzzzzzz",
            url: "/c/D-H-IMPULSE-NAIL-%26-3-FUEL-VALUE-PACK-3-15-X-90MM-BRIGHT-1000PK/p/5080999",
          },
          quantity: 1,
          retailPrice: {
            currencyIso: "NZD",
            formattedValue: "$8.00",
            priceType: "BUY",
            value: 8.0,
          },
          totalPrice: {
            currencyIso: "NZD",
            formattedValue: "$10.00",
            priceType: "BUY",
            value: 10.0,
          },
          unit: "KGM",
          updateable: true,
        },
      ],
      pagination: {
        currentPage: 0,
        pageSize: 10,
        totalPages: 1,
        totalResults: 2,
      },
    },
    fetching: false,
    ownProduct: {
      entriesCount: 3,
      entry: {
        availableForPickup: true,
        configurationInfos: [],
        decimalQty: 33.0,
        deliveryOrder: true,
        entryNumber: 2,
        product: {
          availableForPickup: true,
          baseOptions: [],
          categories: [],
          code: "3250974",
          configurable: false,
          description:
            "The Firth Dricon Rapidset 25 kg Concrete Bag is designed to use on deck posts and fence posts. Pre-mixed concrete bag consists of special additives that cures the concrete set in just 15 minutes. The setting time is fast in warm conditions and slow in cold conditions.",
          expressOrder: true,
          hasNoQuantity: 25.0,
          manufacturer: "Dricon",
          manufacturerId: "RS25",
          name: "Rapidset 25kg",
          purchasable: true,
          sellOrderMultiple: 0.0,
          stock: {
            stockLevel: 0,
            stockLevelStatus: "outOfStock",
          },
          timberProductFlag: false,
          unitCode: "BG",
          uomFormat: "11",
          url: "/c/Rapidset-25kg/p/3250974",
        },
        quantity: 1,
        totalPrice: {
          currencyIso: "NZD",
          value: 125.0,
        },
        unit: "BG",
      },
      isCustomProduct: false,
      quantity: 1,
      quantityAdded: 1,
      statusCode: "success",
      subTotal: {
        currencyIso: "NZD",
        value: 255.0,
      },
    },
  },
};
